### PR TITLE
少许修改

### PR DESCRIPTION
**Pull request by trustgit**
闲的没事 有不当之处请回退（话说github是不是和mw一样有回退来着？）

### CODE REVIEW

**Comment by kj415j45** [comment]
最好不要在gayhub上面使用中文commit message
这样不利于多人协作,尽管你维护的是中文wiki

**Comment by sr229** [comment]
Is this still being worked on? If not, we might close this due to inactivity.

**Comment by kj415j45** [comment]
@sr229 it seems not,i've mention that he is just fix typo,not translate the **new** one

**Comment by sr229** [comment]
then this is marked as a obsolete PR then I believe.

**Comment by Repflez** [comment]
Closed due to inactivity

**Pull request closed without merging**
