### PR TITLE
[FR] Update `Tournaments`

### PR DESCRIPTION
**Pull request by Soetch**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by DoryanR** [comment]
I had a look at the modifications on Visual Studio Code, and I noticed that there are some parity problems between the two articles :

- In the format of the links in the table title, in the links redirecting to the tournaments, and in the format of the links (to be changed to dd/mm/yyyy to have the same format)

Code_YuMLEnF4or

- Also missing are the tournaments, including `PERAK osu! Tournament`.
- Some tournaments are badly sorted by alphabetical order (L286, L105, L179, L228, and so on)

I didn't watch everything, but there are a lot of things to review.

**Comment by Soetch** [comment]
Hum, I'll commit the changes I did, but I don't have time to edit it all. Someone can continue editing it since it's half done, but I can't finish it. I'll try working on it when I have time, but not in the next 2 weeks.

**Comment by TPGPL** [comment]
you probably need to nuke your branch and start from the beginning as something weird happened to your translation

**Comment by TPGPL** [comment]
I'm gonna close this one, as the diff is completely broken and the translation is still outdated

**Pull request closed without merging**
