### PR TITLE
Remove system file formats

### PR DESCRIPTION
**Pull request by The-Last-Cookie**
This is a first step to [#6007](https://github.com/ppy/osu-wiki/issues/6007). The issue [#2709](https://github.com/ppy/osu-wiki/issues/2709) is also kinda loosely related.

The links to the page were removed from every file. I didn't find any mention of `wiki/osu!_File_Formats/Db_(file_format)` elsewhere in the wiki (I searched for `Db_(file_format)`).

I don't know how to open a PR for the wiki at the osu repository, so I would need help with that in case I should add the new files there.

### CODE REVIEW

**Comment by TicClick** [comment]
instead of removing any mention of the `.db` format, I'd suggest simply redirecting the links to the ppy/osu wiki when the content is there

**Comment by The-Last-Cookie** [comment]
After writing a small [python script](https://github.com/The-Last-Cookie/treesearch/blob/master/treesearch.py), I found a few other occurences of `.db`. Just adding this for visibility for now.
When the article on the osu repository is implemented, I will change every file to your suggestion because I think this is better than just removing the links. 👍

**Comment by Walavouchey** [comment]
Just for the sake of being explicit, please hold off on merging this until someone with access to the `ppy/osu` wiki has moved the documentation over.

**Comment by peppy** [comment]
https://github.com/ppy/osu/wiki/Legacy-database-file-structure

**Review by peppy — APPROVED** [review]

**Pull request merged**
