### PR TITLE
Fixes to Hit Objects section

### PR DESCRIPTION
**Pull request by Shadowtail117**
Mostly grammar fixes and an update for the spinner section. Casing for the terms themselves (e.g. hit circle vs. Hit Circle) is up to discussion.

### CODE REVIEW

**Comment by Shadowtail117** [comment]
So...is this good to go?

**Comment by MegaApplePi** [comment]
Well, is this ready to be reviewed?

**Comment by MegaApplePi** [comment]
Well, is this ready to be merged?

**Comment by Shadowtail117** [comment]
Yeah. No conflicts, and I believe I fixed everything.

**Comment by MegaApplePi** [comment]
alrighty, I will ping Repflez to merge. (When your pull request has been reviewed and is ready to be merged, we usually ping Repflez on the osu!dev discord to merge it).

**Pull request merged**
