### PR TITLE
[ES] Add `Account Restrictions`

### PR DESCRIPTION
**Pull request by Coolrmsil**
spanish translation of the Account Restrictions wiki article

- [x] ~~The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)~~

### CODE REVIEW

**Comment by RushFTK** [comment]
hello! thx for taking time to contribute with osu!wiki.   
however, maybe you could standardization your title , like [ES] Update ` Account Restrictions`. thx!

**Comment by Coolrmsil** [comment]
changed title from es.md to [ES] Account Restrictions

**Comment by RushFTK** [comment]
if i'm not make mistake, i still think using following title may better, but it's up to you.
````
 [ES] Update `Account Restrictions`
````

**Comment by Walavouchey** [comment]
a maintainer will do a merge commit to update the branch right before the pr is merged, so there is no need to that yourself.

**Comment by Walavouchey** [comment]
some changes were made to this article in [#7019](https://github.com/ppy/osu-wiki/pull/7019/files#diff-fa533672eaf493e23c962ae89842a000432680910fd4e59e8cfd460ca4724347)

**Review by Walavouchey — APPROVED** [review]
merging as outdated

**Pull request merged**
