### PR TITLE
[IT] Multiple fixes in italian translations

### PR DESCRIPTION
**Pull request by felysu**
There's a lot of phrases/words translated word-by-word (as if it were done with google translate) on the osu!wiki italian pages and various little grammar mistakes that makes it really hard for anyone to understand what's written on certain pharagraps, I'm trying to fix most of them.

### CODE REVIEW

**Comment by sr229** [comment]
Next time, however small the change was, please still describe your changes like what you did earlier, thanks!

**Comment by felysu** [comment]
> Next time, however small the change was, please still describe your changes like what you did earlier, thanks!

Ah, I'm truly sorry. I don't know much about how github works and although I've tried my best to follow the guide on the osu! wiki, I guess I misunderstood about how pull requests work - is it okay if I keep saving things on the branch of this thread if I give detailed descriptions of the changes?

**Comment by WalterToro** [comment]
Hi!
Thanks for taking your first steps into the osu! wiki, we are thankful that you wanna help us, specially with translations, some hints for you:
- Please use commit names and evade the usage of default commit names (like "Update it.md").
- The [https://osu.ppy.sh/help/wiki/Article_Styling_Criteria](Article Styling Criteria) is a must read, all articles should follow this.
- If you are currently working on an article you can create a Draft so we know that is a Work in Progress, if not you can ping me or @TPGPL here or on the osu! Dev Discord Server so we can add or remove that label on your PR.

Again, we are thankful and we hope we can see more contributions from you! :)

**Comment by felysu** [comment]
> Hi!
> Thanks for taking your first steps into the osu! wiki, we are thankful that you wanna help us, specially with translations, some hints for you:
> 
> * Please use commit names and evade the usage of default commit names (like "Update it.md").
> * The [Article Styling Criteria](https://osu.ppy.sh/help/wiki/Article_Styling_Criteria) is a must read, all articles should follow this.
> * If you are currently working on an article you can create a Draft so we know that is a Work in Progress, if not you can ping me or @TPGPL here or on the osu! Dev Discord Server so we can add or remove that label on your PR.
> 
> Again, we are thankful and we hope we can see more contributions from you! :)

Thank you for the explanation! I'll be more careful overall and will read the criterias.

**Comment by cl8n** [comment]
removing wip label since these changes can stand on their own and there haven't been updates in months

**Pull request merged**
