### PR TITLE
Add New Featured Artist: Frums newspost

### PR DESCRIPTION
**Pull request by Ephemeralis**
🎵

### CODE REVIEW

**Comment by nl-tatatat** [comment]
I guessed the FA first tho..

**Comment by nl-tatatat** [comment]
https://twitter.com/Tatatat01/status/1227351523249860612

**Comment by Ephemeralis** [comment]
so you did!

**Comment by nl-tatatat** [comment]
if you want, you can credit me as osu! user tatatat https://osu.ppy.sh/users/6107943 as thats who I am, instead of the twitter handle.

**Pull request merged**
