### PR TITLE
[RU] Update "Ranking Criteria"

### PR DESCRIPTION
**Pull request by AnnSur**
Uрdаtеd trаnslаtiоn оf Rаnking Сritеriа

### CODE REVIEW

**Comment by TicClick** [comment]
gonna chime in later and comment

**Comment by cl8n** [comment]
@TicClick do u want to review this still ?

**Comment by TicClick** [comment]
yes, and I apologize for the delay; will return to it in a few days
(hopefully it's not an issue)

**Comment by cl8n** [comment]
no rush, just wondering

**Pull request merged**
