### PR TITLE
wiki root directory cleanup

### PR DESCRIPTION
**Pull request by RaikireHiuduo**
Moving folders around. All links are not fixed and fully assumed broken. Branch link: https://github.com/RaikireHiuduo/osu-wiki/tree/shuffle/wiki

Idea (I forgot the term, so this is a placeholder):-

- Beatmap = Public explanation
  - Beatmapping = How to make a beatmap, aka offline editing a beatmap.
- Storyboard = Public storyboard explanation
   - Storyboarding = How to make a storyboard, aka Beatmap_Editor's Design and SBS.
- Modding = How to make a mod, or web modding beatmap.

Let me just say this, that linking for mapping guides will be a __\*\*beep\*\*__ since everything is everywhere.

Folders of interest (aka where are those folders now?):-

Major:-

- Added ``Beatmap_Editor_Guides`` at root.
  - Any guide-like stuff was put here for now.
  - ~~``AiBat`` and ``AiMod`` is here for now.~~
     - /Editor/AiMod and /Tools/AiBat.
  - No index page. ``List_of_Guides`` index page reference these.
- ``Beatmap_Editor``
  - Any wiki-like that CAN BE SEEN ON THE EDITOR content was put here for now.
  - Index page is based on the tabs in the editor, and some other stuff related to it.
- ``List_of_Guides``
  - Moved general guide **not** related to beatmapping here.
  - ``Beginner`` seems to reference ``Tablet_purchase``. Put it here?
- Modding
  - Dealing with web related stuffs for beatmaps.
- Tools added in root.
- Storyboards
   - Public explanation about Storyboard, and significance, and maps.

Minor:-

- Game_Modes
  - ``External_Ports``
    - ``osu!MapDownloader`` (unofficial mobile client to download beatmap from bloodcat)
- ``Submission``
  - ``Beatmap_Ranking_Procedure``
- ``Tournaments``
  - ``Countries_that_participated_in_osu!_tournaments``
  - ``osu!_Tag_Team_Multiplayer_Tournament``
- ``Storyboarding``
  - ``osu!_File_Toggles``

Gray area (aka I have no idea):-

- Two
  - ``Beginner`` (Guide-like explanation for starting out with hardware to use and to playing with osu!standard for the first time), 
  - ``FAQ`` (`/p/faq`, aka key points of Game_Modes, and of course, FAQ), and
  - ``Welcome`` (user/wiki-meta page?)

Clear:-

- One
  - ``Bancho`` (requested to keep; ambiguous index page with explanation for Bancho and BanchoBot), and 
  - ``BanchoBot`` (a user account and the osu!chat bot commands)
     - Killed Bancho.
- Three
  - ~~``About`` (two lines, about osu!)~~ Keep.
- Four
  - ``Modding`` (wikipage for modding in general)
  - ``Modding_and_Mapping`` (looks like a sticked forum topic about mod)
     - Modding is parent.
- Five
  - ~~``Report`` (ru.md ONLY. Looks like Report_system below), and~~ removed
  - ~~``Report_System`` (en.md ONLY. Looks like Report above)~~ removed
     - Both put into Reporting_Bad_Behaviour
- Six
  - ``Storyboarding`` (Previously was used to describe what is a storyboard and examples of storyboarded beatmaps; now is storing also SBS and Design's stuffs)
     - Separated.

Deleted:-

Not written in English, and short enough to be put on Glossary.

- Guest_Difficulty
- Mappers
- Ranked_beatmap
- Star_Priority
- Slider Velocity
- Ambiguous pages (Mod, and Bancho)

Known broken page:-

- Audio Editing
  - Deleted Creative_Commons (used at the end of the line) on my previous PR ( #112 )
- meta folder ( #18 )
  - Entry-Not-Found was supposedly used as a default message answer when not found on wiki for osu-web to point to.

### CODE REVIEW

**Comment by TPGPL** [comment]
Editor_guides -> Editor_Guides

**Comment by RaikireHiuduo** [comment]
@TPGPL Weirdly, Git ignores letter capitalisation of `G`. No idea how to enforce capital `G` as of now.

**Comment by TPGPL** [comment]
Why moving Storyboards out Storyboarding

**Comment by RaikireHiuduo** [comment]
Same reason as separating Beatmapping and Beatmaps.

The original content was explaining Storyboards in general (https://osu.ppy.sh/wiki/Storyboarding, 

I admit that the naming convention in MediaWiki is pretty non-intuitive when it comes to mappin', and no mention on how to make one (which only BE's Design and SBS seeems to provide the most documentation).

**Comment by TPGPL** [comment]
You could change `Storyboarding` to `Storyboard_Scripting` as all articles in it are related to this topic. You could also shorten all subfolders by `Storyboard_Scripting`
e.g. `Storyboard_Scripting_Commands` into `Commands`

**Comment by RaikireHiuduo** [comment]
There are two official ways excluding tools like SGL.

One is visually by Design (located in Beatmap_Editor), and another is SBS (which is in Storyboarding for now).

My current dilemma now is that I want to keep Storyboarding as a index page on how to do storyboard the same way as Beatmapping is a index (I lied, it is a carbon copy of `/p/faq/`, and still looks kool after so long) page on how to make a beatmap.

**Comment by TPGPL** [comment]
probably capitalize `Beatmap_forum`

**Pull request merged**
