### PR TITLE
[en] Upgrading to lazer (typo)

### PR DESCRIPTION
**Pull request by icecream17**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

SKIP_OUTDATED_CHECK

### CODE REVIEW

**Comment by peppy** [comment]
https://idioms.thefreedictionary.com/at+the+least

**Comment by icecream17** [comment]
I'm confused because this pr adds the word "the" in "at the (very) least" but oh well

**Review by TicClick — COMMENTED** [review]
this looks like a [valid change](https://ell.stackexchange.com/a/60139), ~~going to reopen the PR~~ welp, the branch is already removed..

I get that it's a miniscule thing, worth fixing still

**Comment by peppy** [comment]
Please don't. This is an osu! wiki, not a grammar nazi wiki. It's valid english.

**Pull request closed without merging**
