### PR TITLE
Variables names weren't shown

### PR DESCRIPTION
**Pull request by Beafantles**
- `<>` are considered as tags in HTML so the variables names weren't shown. We should rather use ` to correctly embed variables names.
- A blank line is needed to print a line break.
- Incorrect hyperlinks.

### CODE REVIEW

**Comment by MegaApplePi** [comment]
@Beafantles The internal links are correct when viewing the article live on the site. It is intended that they just point to the directory, not a file. If you want to see for yourself, here is an example:
- <https://osu.ppy.sh/wiki/Beatmaps/en.md>
- <https://osu.ppy.sh/wiki/Beatmaps>

**Comment by Beafantles** [comment]
You're right, there is still an error though. This should be `/wiki/Skinning/skin.ini` and not `/wiki/Skinning/Skin.ini`. My branch is out-of-date now, should I update it, make the changes again (correcting this mistake), and make another pull request?

**Comment by MegaApplePi** [comment]
The files you modified were updated 4 to 8 months ago, so you shouldn't need to update the branch.

**Comment by Beafantles** [comment]
This should be fine now?

**Comment by Beafantles** [comment]
The file `wiki/Storyboard_Scripting/Miscellaneous/en.md` has been deleted actually. I don't really know why but my commits on this file doesn't make sense anymore so. Should I remove this file from my commits or should I actually rewrite the entire file to resolve this conflict?

**Comment by Beafantles** [comment]
As soon as `wiki/Storyboard_Scripting/Miscellaneous/ja.md` will be deleted, this conflict will be resolved. Keeping `ja.md` doesn't make sense in my opinion, since `en.md` got deleted.

**Comment by osuShiro** [comment]
Requesting an update on this (and conflict fixing)

**Comment by sr229** [comment]
Change is since last November 21, 2017, this is stale, recommending to close this

**Comment by WalterToro** [comment]
Closing this due to over a year of inactivity

**Pull request closed without merging**
