### PR TITLE
Group news posts by year

### PR DESCRIPTION
**Pull request by Walavouchey**
- [x] depends on https://github.com/ppy/osu-web/pull/9280
- [x] update link ci check
- [x] ~~update remark (???)~~ pretty sure remark is just complaining about old posts with bad formatting
- [x] depends on https://github.com/ppy/osu-wiki/pull/8577

@nanaya please check if this is correct (e.g. do news post links need to be updated?)

<details><summary>script</summary>

```py
import os
import shutil

dirs = set()

for file in os.listdir("news"):
    if not file.endswith(".md"):
        continue
    year = file[0:file.find("-")]
    if year not in dirs:
        dirs.add(year)
        os.mkdir(f"news/{year}")
    shutil.move(f"news/{file}", f"news/{year}/{file}")

os.system('git add news/201* news/202*')
os.system('git commit news -m "group news posts by year"')
```

</details>

### CODE REVIEW

**Comment by RockRoller01** [comment]
won't this break the check for broken wiki links, as it isn't aware of the new structure for news links?

**Comment by Walavouchey** [comment]
yes (for news post links) which is why i put it on the task list

**Comment by RockRoller01** [comment]
somehow glossed past that list point... guess im blind

**Comment by nanaya** [comment]
there's no change on osu-web side links

**Review by peppy — APPROVED** [review]

**Pull request merged**
