### PR TITLE
Add final member of the osu!taiko pp committee

### PR DESCRIPTION
**Pull request by Lawtrohux**
This adds the final member of the osu!taiko pp committee, and changes the wording as active changes are now implemented.

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

`SKIP_OUTDATED_CHECK`

### CODE REVIEW

**Review by TPGPL — APPROVED** [review]
looks ok

**Comment by Walavouchey** [comment]
the new table row can be copied to the translations while keeping the outdated marker if changing the one paragraph is too much trouble

**Review by TPGPL — APPROVED** [review]
lgtm

**Review by Walavouchey — APPROVED** [review]
outdated hash check failed for some reason, will investigate

https://github.com/ppy/osu-wiki/runs/7468467079?check_suite_focus=true

**Pull request merged**
