### PR TITLE
OWCG updates

### PR DESCRIPTION
**Pull request by sr229**
As per request and discussion, OWCG has to be trimmed down

- Other parts are trimmed down. Only the actual needed parts are left.
- The other parts were retrofitted.
- the only way to narrow OWCG is to assume they know Git. Oh well... :dancer:

### CODE REVIEW

**Comment by sr229** [comment]
don't mind the fuck up I did :dancer:

**Comment by Loctav** [comment]
I thought we agreed on basing the owcg on the github client, not on console commands (https://desktop.github.com/)

**Comment by sr229** [comment]
Pinning Checklist

- [ ] Local version needs to be based around GitHub Desktop.
- [ ] Narrow down OWCG more.

**Comment by RaikireHiuduo** [comment]
`.zip` because GitHub do not accept `.md` upload.

The files from #333 . Planning to delete the `contribute` branch soon™️ (it serves as a backup for now).

[PR333RH.zip](https://github.com/ppy/osu-wiki/files/1105959/PR333RH.zip)

**Comment by sr229** [comment]
Update: This PR may become more stale because I have other projects to do. Do not close this yet as this is still in a WIP state.

**Comment by sr229** [comment]
Requesting Preliminary review from @TPGPL  @MegaApplePi  or @kj415j45

**Comment by MegaApplePi** [comment]
its still long :<
and a few osu-wiki/web info is out of date... or at least one that I found

**Comment by sr229** [comment]
@MegaApplePi it's still WIP, so it's better to review it while it's still in a rough and unfinished state

**Comment by MegaApplePi** [comment]
Wouldn't it be best to just throw this one under the bus and start from scratch?

**Comment by sr229** [comment]
sounds like it.

TBH I'm workng a ground-up rewirte very soon

**Comment by TPGPL** [comment]
See #513

**Pull request closed without merging**
