### PR TITLE
Convert images?

### PR DESCRIPTION
**Pull request by TPGPL**
Opening this PR to get an opinion. If it gets approved, I'll change links in files

### CODE REVIEW

**Comment by MegaApplePi** [comment]
I am going through them with prs #215 #219 #220

**Comment by TPGPL** [comment]
so i guess i should close it?

**Comment by MegaApplePi** [comment]
I was using that electron application that I wrote (which I told you about)...
With that, I was going to check:
- markdown
  - level 6 headings
  - multiple level 1 headings
  - images inside tables
  - lists inside tables
- links
  - http
  - internal file links
  - 404'd (and 405 and 503)
- images
  - broken linked images
  - png
  - wide images (width > 720px)

Since the osu-web gives osu-wiki only 720 pixels width only, I decided to downscale them to fit that width. Also, since Repflez was noting that the repo size was nearing 1GB, I also decided to use `FileOptimizer` to help decrease the overall size...

**Comment by MegaApplePi** [comment]
and convert pngs with no transparency to jpg.. but ¯\\\_(ツ)\_\/¯... I guess you should close this since it will lead to a mass of failed image loading... unless they were taken care of

**Comment by MegaApplePi** [comment]
also, not _all_ images should use jpg... only the images with an alpha channel (those with transparency) should only use jpg

**Pull request closed without merging**
