### PR TITLE
[ES] Update `Reporting bad behaviour`

### PR DESCRIPTION
**Pull request by UnknownOsu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

I changed some photos because I couldn't find the user in the report photos in the profile, so I put my profile instead. I did the same with the other photos.

The [report beatmap picture](https://github.com/ppy/osu-wiki/blob/master/wiki/Reporting_bad_behaviour/img/report-beatmap.png) I left it unchanged because the [report beatmap button](https://i.imgur.com/DpqQrMt.png) is currently missing. So I left it as it was.

Tell me if any picture is wrong, I will change it as soon as possible.

### CODE REVIEW

**Review by agatemosu — COMMENTED** [review]
It's really necessary?

**Comment by UnknownOsu** [comment]
Why not? If there is the possibility of putting it in Spanish, I think it would be better for the reader.

**Comment by TicClick** [comment]
it's been slightly more than a month now, is this ready to be merged?

**Comment by UnknownOsu** [comment]
According to me, yes, unless there is something missing.

**Review by TicClick — APPROVED** [review]

**Pull request merged**
