### PR TITLE
Add integration for Visual Studio Code

### PR DESCRIPTION
**Pull request by sr229**
This includes [`vscode-remark`](https://github.com/mrmlnc/vscode-remark) and a lint command to run a wiki-wide lint.

image

However, this does not include integration for other editors, hence the inclusion of the `lint:wiki` command as a way for users with other editors to lint locally on the fly.

### CODE REVIEW

**Comment by sr229** [comment]
So getting an issue that remark is ignoring the configuration inside `news/` not sure if that's intended.

**Comment by sr229** [comment]
Marking ready for review, going to fix the problem with news in another PR.

**Comment by cl8n** [comment]
lint:wiki doesn't seem very useful because you're usually only running this on files you edit. also it forces all these options I wouldn't want to use every time. I think it's easy enough to run remark already if you want to

**Comment by sr229** [comment]
> lint:wiki doesn't seem very useful because you're usually only running this on files you edit. also it forces all these options I wouldn't want to use every time. I think it's easy enough to run remark already if you want to

Its forcing an option per se, it just makes the linting part easier for the end user since they don't need to run `npx remark` everytime and remember the actual command line arguments. `yarn lint:wiki` is easier to remember vs `npx remark <arg> <arg>`.

**Comment by cl8n** [comment]
why would u want to be using any of these options by default, only way I've ever needed to run this was `remark <files I'm editing>`

**Comment by peppy** [comment]
How does this actually show linting results? I can't seem to see anything.

**Comment by sr229** [comment]
@peppy it only shows errors when it sees one, otherwise it returns a zero exit code.

**Comment by peppy** [comment]
I was testing with errors and saw no results. Is this working for others?

**Comment by TPGPL** [comment]
Closing as it doesn't seem really useful in its current form as it doesn't errors directly in code, plus the branch was deleted

**Pull request closed without merging**
