### PR TITLE
Fixed some things in this English Article and added some things

### PR DESCRIPTION
**Pull request by sr229**
probably the most ugliest around here. Fixed some to Markdown

still WIP

unfortunately because MD is limited by design, I cannot unuse some HTML around here such as the font size

which is according to [this stack exchange topic](http://meta.stackexchange.com/questions/170480/is-it-possible-to-change-the-text-size-in-the-code-markdown). the text sizing is entirely up to the site.

### CODE REVIEW

**Comment by sr229** [comment]
I want your feedback out of this guys. I will try do the same on HTML-infested articles but it depends on the severity and the limits of the Markdown language

**Comment by MegaApplePi** [comment]
Use images for the examples, when necessary

**Comment by sr229** [comment]
I think that can be done fairly quickly, will do that once I get home.

**Comment by TPGPL** [comment]
I'm already fixing Installation. There is even a PR, so you can see how I have ported it.

**Comment by TPGPL** [comment]
Also, add title to BBCode with `====` header and reduce headers' grade by 1 (like `###` into `####`)

**Comment by sr229** [comment]
Updated to resolve Conflicts

**Comment by sr229** [comment]
Closed for Inactivity

**Pull request closed without merging**
