### PR TITLE
Unify list item indent in wiki articles

### PR DESCRIPTION
**Pull request by TPGPL**
used `^ {0,}[0-9]{1,2}\. {2,}` and `^ {0,}-{1} {2,}` + remark for searching

Branch comparison by remark warnings:
- master
  - `⚠ 13391 warnings`
- list-indent
  - `⚠ 8877 warnings`

### CODE REVIEW

**Comment by cl8n** [comment]
pls https://github.com/ppy/osu-wiki/pull/3773#issuecomment-650607240
pretty sure this part is covered by `listItemIndent: '1'` too

**Comment by TPGPL** [comment]
well the only reason i did this *manually* was because [list item content indent rule](https://github.com/remarkjs/remark-lint/tree/main/packages/remark-lint-list-item-content-indent) doesn't have a stringify, so even if we used `listItemIndent: 1`, the indents would still be wrong

**Comment by cl8n** [comment]
it doesn't have a setting, but it doesn't add extra spaces where they have no meaning, which is what we want anyway. do you have any examples where it came out wrong? I tested on a few samples from the diff here

also it turns out we don't have lint configured right to catch some of these. for example this passes
<details>
<summary>example</summary>

```markdown
1. Kunjungi [subforum skinning](https://osu.ppy.sh/community/forums/15) dan cari skin yang anda sukai.
2. Setelah anda menemukan skin, unduh skinnya.
3. Bergantung pada bagaimana skinner mengemas skin mereka, anda perlu melakukan hal yang berbeda.
   - Jika skin menggunakan `.osk`:
     1. Buka filenya atau seret dan lepaskan ke osu! yang sedang dijalankan.
     2. osu! akan memproses skin dan secara otomatis akan memilihnya untuk anda.
   - Jika skin dikompresi (menggunakan `.7z`, `.rar`, `.zip`, dll.):
       1. Extract filenya.
       2. Pindahkan folder skin ke folder `Skins` di direktori osu!.
       3. Jika osu! sedang dijalankan, anda mungkin perlu memulai ulang sebelum skin dapat digunakan.
       4. Di osu!, pilih menu [Pengaturan](/wiki/Options) dan cari `Skin`.
       5. Gulir ke bawah ke opsi `Skin saat ini:` dan pilih skin yang telah anda unduh.
```

</details>

**Comment by TPGPL** [comment]
It required adding additional spaces for `Ranking_Criteria/osu!mania/ko.md` for example. I think that there just weren't many examples of lists lacking spaces for their list items and most errors were coming from too far-indented items if that's what you meant.

**Pull request merged**
