### PR TITLE
Replace winner badge image for osb! Storyboarding Contest #1

### PR DESCRIPTION
**Pull request by ZeroPyrozen**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by Walavouchey** [comment]
[TheDuckMask's profile](https://osu.ppy.sh/users/7405768)

image

**Review by Walavouchey — APPROVED** [review]

**Comment by Walavouchey** [comment]
Was there something @Ephemeralis needed to check here? It looks correct - the current image must've been an old revision or something.

**Comment by peppy** [comment]
It's fine if you're confident, just seems weird that badges are changed after the fact. If it matches the one on the profile it should be fine.

**Comment by Walavouchey** [comment]
My brain must've somehow thought I was looking at the same picture when reviewing, my bad.

**Pull request merged**
