### PR TITLE
Disable CI workflow runs for the master branch

### PR DESCRIPTION
**Pull request by Walavouchey**
they're only redundant since all changes are run through them via pull requests anyway, and they pointlessly keep failing when they are skipped

[context](https://discord.com/channels/188630481301012481/218677502141399041/993418941454102619)

### CODE REVIEW

**Comment by peppy** [comment]
Any specific reason for doing this? They seem to be completing quite fast so I'd probably just let it be unless there's a good reason.

**Comment by Walavouchey** [comment]
not really other than failing whenever they are skipped, and although that can be fixed more surgically, me and clayton figured they might not be necessary at all. close if you will.

**Comment by cl8n** [comment]
also, this workflow *doesn't* check that the whole repo is in a valid state at this commit, so it was kind of odd to run on master to begin with

**Comment by peppy** [comment]
Yeah it is a bit weird that it doesn't check everything. Probably need to eventually have a separate workflow for that so we can see the overall status. Maybe.

**Comment by TicClick** [comment]
would rather make a proper fix which I never really implemented

**Review by TicClick — APPROVED** [review]

**Comment by cl8n** [comment]
will revisit CI on master when we're able to run checks on more than just changed files

**Review by cl8n — APPROVED** [review]

**Pull request merged**
