### PR TITLE
Add more songs to `osu! originals`

### PR DESCRIPTION
**Pull request by Walavouchey**
i was working on this yesterday and i just noticed the owc semifinals tiebreaker got a custom track lol

### songs added

in fa catalogue (need ORIGINAL label on the website @Ephemeralis):

- happy30 - As the wind blows
- happy30 - You spin my world
- happy30 - Circles!
  - for the fa announcement, it was renamed and published "officially", meaning the current spotify link is more suitable. since it did first appear for the contest submission it'll be kept in that section
- happy30 - Relentless
- happy30 - Shoot the star

` [^fa-catalogue]` footnote added

- Kuba Oms - My Love (Redside Remix) (feat. Hatsune Miku)

not in fa catalogue:

- Porter Robinson & Madeon - Shelter (happy30 Remix)
- Kurokotei feat. Sennzai - escape (the looking-glass, and what alice found there)
- ikaruga_nex vs. Kagetora. - Grabinschrift der Gotter
- katagiri - Bootleg Heaven
- Down - Down
- Redside - Sidequest
- Thaehan - All or nothing
- Apollo - SCUNTHORPE
- Down - AJT
- Down - Yamangomcpro6th

### remarks

- consulted happy30 for the case of their songs, the ones in the album were all made for the fa announcement
- if any GTS-related people happen to look then please verify i haven't forgotten anything
- thinking these "Featured in {contest}" notes aren't that relevant for the songs themselves, it's not like they were first published for those contests, thoughts @Nivalyx 
- i wonder what area label a pr for this article (and others related to featured artists) should have

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review) @Pisapou @agatemosu

### CODE REVIEW

**Review by agatemosu — APPROVED** [review]
(Spanish) Good

**Review by Pisapou — DISMISSED** [review]
(French) is also good

**Comment by Kasumiikun** [comment]
All GTS stuff looks good to me, didn't notice ULTIMATE still didn't have its proper release link as well though, here it is: https://m.soundcloud.com/5kilobyte/ultimate

**Comment by Nivalyx** [comment]
> thinking these "Featured in {contest}" notes aren't that relevant for the songs themselves, it's not like they were first published for those contests, thoughts @Nivalyx

yeah, it should be okay if these are to be removed i guess

**Comment by Ephemeralis** [comment]
happy30's tracks are now set on the website as osu! originals.

**Comment by Walavouchey** [comment]
added a few more songs and removed a couple notes. this does make some tables look a little barren, but maybe we can add something like album links, come up with a good way to split soundcloud/youtube/fa listing links, or any other formatting improvements one may think of. i believe this makes the tables cleaner for now though

@Ephemeralis

noticed in passing that [Kuba Oms - My Love (Redside Remix) (feat. Hatsune Miku)](https://osu.ppy.sh/beatmaps/artists/tracks?artist=Redside&is_default_sort=true&query=%22My%20Love%20(Redside%20Remix)%20(feat.%20Hatsune%20Miku)%22&sort=relevance_desc) needs the `ORIGINAL` tag

**Review by TPGPL — DISMISSED** [review]

**Review by TPGPL — APPROVED** [review]

**Pull request merged**
