### PR TITLE
[FR] Welcome: fix typo

### PR DESCRIPTION
**Pull request by leonekmi**
Typo error

### CODE REVIEW

**Comment by MegaApplePi** [comment]
Please change the title of this pull request to something more meaningful like `[FR] Welcome: fix typo`.
Also, use more descriptive commit messages.

**Comment by RedNesto** [comment]
And please keep in mind this page is out of date. My translation pr for the french welcome page is waiting for too long :x

**Comment by apap04** [comment]
@RedNesto what's the PR tag?

**Comment by RedNesto** [comment]
@apap04 pr #274

**Comment by turbedi** [comment]
This PR can be closed, it is already fixed by PR #481

**Pull request closed without merging**
