### PR TITLE
Updated 'The Team' wiki listings and Staff Log

### PR DESCRIPTION
**Pull request by Blooshing**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] copy changes to translations

### CODE REVIEW

**Comment by peppy** [comment]
Feels like this should be automated listings rather than manually updated each time..

**Comment by Walavouchey** [comment]
if only they were automated pages like the user group listings... (e.g. like https://osu.ppy.sh/groups/28)

**Comment by Walavouchey** [comment]
there's an issue tracking this at https://github.com/ppy/osu-web/issues/6216

**Comment by cl8n** [comment]
`osu-wiki translate-groups` from <https://github.com/cl8n/osu-wiki-bin> can do the translations at least, which is the most tedious part. it's why `meta/group-info` exists in this repo. all the past people who regularly updated group pages used this, and the wiki pages should probably include a comment saying you don't have to do this by hand...

as for osu-web progress, Staff Log is close to having a replacement, I just need to put together a frontend and do a final pass over everything. most of the code is already in master.
the reason group listings are duplicated to osu-wiki is bc some extra info has nowhere to go on osu-web: areas of focus, other fluent languages, etc

**Review by Walavouchey — APPROVED** [review]

**Pull request merged**
