### PR TITLE
[PT-BR] Add `Skinning/osu!mania`

### PR DESCRIPTION
**Pull request by Icaro1447**

### CODE REVIEW

**Review by Sebola3461 — DISMISSED** [review]
good job

**Comment by TicClick** [comment]
before this is merged, you've got a couple of headings, like `Lighting`, or `Long Notes`, untranslated — is that intended?

**Comment by Icaro1447** [comment]
> before this is merged, you've got a couple of headings, like `Lighting`, or `Long Notes`, untranslated — is that intended?

gotta fix it, but long note is a basic term and in portuguese would be really weird and players would not understand it properly (unless its intended to be all translated, but i checked french and there is english terms there aswell). same for other stuff on the translation.

**Comment by TicClick** [comment]
> unless its intended to be all translated

it isn't, many terms in other languages are borrowed as-is

**Review by TicClick — APPROVED** [review]

**Pull request merged**
