### PR TITLE
Add ARForest Featured Artist newspost

### PR DESCRIPTION
**Pull request by Ephemeralis**
🎵

### CODE REVIEW

**Comment by Nivalyx** [comment]
IT IS FINALLY HERE AAAAAAAAAAAAA ;~;

for the record i was also working on [Infection](https://osu.ppy.sh/beatmapsets/1225001#osu/2559136) actually but idk whether it's a good fit for the newspost or not as the mapset in question is still wip (・・；)

**Comment by Ephemeralis** [comment]
I don't think there's enough room to fit another showcase mapset (especially if it's WIP still) in, usually the limit is 2 + 2 existing + 1 new for preview stuff

**Comment by Nivalyx** [comment]
ah, okie

**Comment by Ephemeralis** [comment]
Added it in anyway, don't see the harm

**Review by peppy — APPROVED** [review]

**Pull request merged**
