### PR TITLE
Add `Project Loved: June 2023` news post

### PR DESCRIPTION
**Pull request by Hiviexd**
already pre-reviewed

todo:

- [x] videos
- [x] packs
- [x] medals
- [x] forum threads

### CODE REVIEW

**Comment by Ephemeralis** [comment]
Videos are updated. Medals are pending, will update when those are available (should be tonight, contingent on peppy availability since it was sorta sprung on him)

**Comment by Ephemeralis** [comment]
Medals are up. Highlight me when you see me around on Discord and we can get forum posts & the rest out.

**Comment by Walavouchey** [comment]
will need to add query strings to the video urls. the taiko video also [needs updating](https://discord.com/channels/188630481301012481/384640068847009792/1120421680964186242)

**Comment by Ephemeralis** [comment]
Taiko video has been updated on S3 and cache has been busted - should be no need for query strings now (hopefully). @Hiviexd if you're around, we can go ahead with threads, etc

**Review by Ephemeralis — APPROVED** [review]

**Pull request merged**
