### PR TITLE
Beatmap Spotlights: May 2017 newspost

### PR DESCRIPTION
**Pull request by Shadowthegod**
Will need to either upload the images to assets or add them in some other way. Also, the tumbler URLs are also missing. Waiting for Loctav.

### CODE REVIEW

**Comment by oralekin** [comment]
You can upload images to the wiki  (through github)

**Comment by Shadowthegod** [comment]
The only problem is, as I have never done this before, I do not know how to do that. Github related articles helped nothing in this matter. So I would appreciate some kind of guide on which is the best way of doing that.

**Comment by oralekin** [comment]
- on github web, open to your directory of choice
- drag file

**Comment by Loctav** [comment]
Upload images to a new folder in `/wiki/shared/news/`, name the new folder according to the announcement title (like the cwc recap does) and put all images into that. Then, in your announcement, refer to the image via ``

**Comment by peppy** [comment]
please learn how to use git before continuing

**Comment by Repflez** [comment]
what the fuck?

**Comment by Loctav** [comment]
Gonna PR a prettier way tomorrow lol

**Pull request closed without merging**
