### PR TITLE
Apply remark linting

### PR DESCRIPTION
**Pull request by peppy**
This is an initial pass of automatic linting using the configuration provided in #3318.

Next steps would be to manually check over these changes and assess which rules (if any) need to change.

For anyone wanting to run this at home, make sure you have an `npm` environment and then install remark and plugins we are using:

```sh
npm i remark-cli remark remark-frontmatter remark-lint-definition-case remark-lint-fenced-code-flag remark-lint-final-definition remark-lint-final-newline remark-lint-list-item-indent remark-lint-list-item-spacing remark-lint-maximum-heading-length remark-lint-maximum-line-length  remark-lint-no-duplicate-definitions remark-lint-no-duplicate-headings remark-lint-no-duplicate-headings-in-section remark-lint-no-emphasis-as-heading remark-lint-no-file-name-articles remark-lint-no-file-name-consecutive-dashes remark-lint-no-file-name-irregular-characters remark-lint-no-file-name-mixed-case remark-lint-no-heading-content-indent remark-lint-no-heading-indent remark-lint-no-heading-like-paragraph remark-lint-no-missing-blank-lines remark-lint-no-shortcut-reference-link remark-lint-no-tabs remark-lint-no-undefined-references remark-lint-no-unused-definitions remark-lint-ordered-list-marker-value remark-lint-table-pipe-alignment
```

to run linting:

```sh
remark . -o
```

### CODE REVIEW

**Comment by MegaApplePi** [comment]
There were a few typos in the config file:
- line 3 should actually be `remark-preset-lint-markdown-style-guide`
- and line 14 should actually be `remark-lint-no-file-name-outer-dashes`

Even so, I tried linting it myself, but it looks like remark is ignoring the config file and uses its default settings.

**Comment by peppy** [comment]
i can confirm it *is* reading the config to some extent, because it is loading the plugins.

**Comment by peppy** [comment]
Updated with proposed changes, see diff.

**Comment by peppy** [comment]
It's quite possible that applying on already applied changes is causing further issues (see escaping of `_` characters). Will open a second PR applying from scratch.

**Comment by peppy** [comment]
Closing for now.

**Pull request closed without merging**
