### PR TITLE
[ID] Add `Upgrading to lazer`

### PR DESCRIPTION
**Pull request by Nivalyx**
yup

@reviewers this article is genuinely \*very\* big and there are quite a bunch of things here that aren't possible to be translated as is, therefore some liberties have to be taken in order to make things sound natural in indonesian.

...so yeah, checks and reviews will be much appreciated as always ( 〃．．) 

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] Apply https://github.com/ppy/osu-wiki/pull/8576

### CODE REVIEW

**Comment by The-Last-Cookie** [comment]
Please don't forget to apply the changes from #8548.

**Comment by Nivalyx** [comment]
,,,e nvm it got fixed by its own 

remark was just being remark i guess :P

**Comment by The-Last-Cookie** [comment]
And there's another one: #8576

**Comment by TicClick** [comment]
> ,,,e nvm it just got fixed on its own
> 
> remark was just being remark for a second there i guess :P

it wasn't remark but https://github.com/ppy/osu-wiki/issues/8553

please apply https://github.com/ppy/osu-wiki/pull/8576 and I can merge this with a "no native review" mark

**Comment by Nivalyx** [comment]
@TicClick sorry for the delay, the changes from #8576 should be added now

**Review by TicClick — APPROVED** [review]
merging (no native review for one week or longer)

**Pull request merged**
