### PR TITLE
Change `Support Team` to `Technical Support Team` in meta information `TRANSLATING`

### PR DESCRIPTION
**Pull request by The-Last-Cookie**
This name change occured in #10425 

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by agatemosu** [comment]
13efa567a883f1c2c47c31f18c2ceee640fbbe14 because is alumni, not current

**Comment by The-Last-Cookie** [comment]
I think the change you are referring to is something else.

The title is probably worded poorly, my bad.

**Comment by agatemosu** [comment]
Still, the command to translate the list of members would not work
https://discord.com/channels/188630481301012481/218677502141399041/1173040277552906282

**Comment by The-Last-Cookie** [comment]
Again, I don't change any XX.yaml file. This PR changes the listing that details which groups are affected by the command in `TRANSLATING.md`. And `Technical Support Team` (instead of just `Support Team`) is now part of this list.

In no way should the command's workflow be troubled by this.

**Comment by agatemosu** [comment]
The yaml changes the table in the Alumni page. The SPT page doesn't need the yaml because only has the languages and will not work because of the message i linked

**Review by TicClick — APPROVED** [review]

**Pull request merged**
