### PR TITLE
[TR] Add `Ranking_Criteria/osu!`

### PR DESCRIPTION
**Pull request by eAkhaten**
This is a fully translation of ranking criteria for osu!

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by zeusminus** [comment]
I will drop a thorough review in the following days. Please do not merge it until then.

@eAkhaten also seems like you need to sync your branch with master, it's outdated.

**Comment by Walavouchey** [comment]
It will be synced before merging anyway, so there's no need to do that yourself.

**Comment by Walavouchey** [comment]
@zeusminus ping

**Comment by TicClick** [comment]
with a few more changes to the RC merged, this is now stale. when returning to the PR, please make sure you have included the latest updates from https://github.com/ppy/osu-wiki/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Amerged+ranking+criteria+label%3A%22area%3Aranking+criteria%22+-label%3A%22area%3Atranslations%22

**Comment by TicClick** [comment]
talked to Zeus, it has to be closed due to low quality and high review overhead, which would boil down to re-doing the translation from scratch

**Pull request closed without merging**
