### PR TITLE
Fix Articles with broken redirects to ASG (which was redone to ASC)

### PR DESCRIPTION
**Pull request by sr229**
### Description

Fixes broken redirects to the old ASG (which is now ASC)

### Status
**Finished**; Pending Merge.

### Changelog
- Patched ``osu!wiki_contribution_guide/en.md`` ``CONTRIBUTING.md`` ``README.md`` and ``.github/PULL_REQUEST_TEMPLATE.md`` with correct redirect.
- Remove gitdiff artifact from ASC.

### CODE REVIEW

**Comment by sr229** [comment]
(I made sure this time I didn't break gitdiff, sorry) 😢

**Comment by sr229** [comment]
Requesting a review from repository administrators to see if I missed something

**Comment by TPGPL** [comment]
u forgot fixing it in Index page

**Comment by sr229** [comment]
@TPGPL which index page?

**Comment by MegaApplePi** [comment]
@sr229 this one <https://osu.ppy.sh/wiki/index>

**Pull request merged**
