### PR TITLE
CWC2021 Conclusion update

### PR DESCRIPTION
**Pull request by WalterToro**
Closes #5694 as is not relevant.

### CODE REVIEW

**Review by TPGPL — COMMENTED** [review]
L11 needs past tense too

**Comment by peppy** [comment]
The podium is the wrong image format and size, as usual. Would appreciate if you can fix your process so I don't have to fix the image each tournament.

**Review by peppy — CHANGES_REQUESTED** [review]
As stated

**Comment by WalterToro** [comment]
> The podium is the wrong image format and size, as usual. Would appreciate if you can fix your process so I don't have to fix the image each tournament.

There is no process, the podium is the image im given on ops, but no issues, i already changed it.

**Review by peppy — APPROVED** [review]

**Pull request merged**
