### PR TITLE
Update spaceman_atlas's description in `osu! team`

### PR DESCRIPTION
**Pull request by iSlodinxOsu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Review by Walavouchey — APPROVED** [review]
squashed commits on request

**Comment by peppy** [comment]
This is bullshit lol

**Comment by peppy** [comment]
Please pass ALL team changes via me.

**Comment by cl8n** [comment]
> This is bullshit lol

I'm not sure what is supposed to be conveyed then by him having the support role on the website. (unless you are also unaware of that?)

**Comment by peppy** [comment]
it's not a team addition, was just required to make certain forum permissions happen. he is not suddenly a support person.

please ask before making team changes on the wiki is all i ask, since they aren't always what they seem.

**Pull request merged**
