### PR TITLE
Fix remaining line endings

### PR DESCRIPTION
**Pull request by Joehuu**

### CODE REVIEW

**Comment by sr229** [comment]
What line endings are precisely we're using here for this file?

**Comment by Joehuu** [comment]
Idk if the problem is even line endings. Some weird thing with these files is that when you save it, the diff does this.

`Ctrl+S` any of these files and it'll show the diff replacing all lines. (I use VS Code.)

**Comment by sr229** [comment]
Doesn't answer my question however, Are we using CRLF or LF initially?

**Comment by Joehuu** [comment]
CRLF, since most files have that.

**Comment by sr229** [comment]
I inquired @Repflez regarding normalizing line endings, I think we should enforce CRLF as our defualt line endings from now on since it was our line endings since the start.

**Pull request merged**
