### PR TITLE
Fix list indentation

### PR DESCRIPTION
**Pull request by agatemosu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

SKIP_OUTDATED_CHECK

### CODE REVIEW

**Comment by TicClick** [comment]
I'm confused, what does this fix/change when done at such scale?

**Comment by cl8n** [comment]
I think the technically-wrong list formatting may have been intentional to support the website's special image container for images alone in a paragraph. will check this one soon

**Comment by cl8n** [comment]
the table thing seems pretty inconsequential to me but i guess asc does say this

> Empty cells must use a vertical bar (`|`) followed by two spaces and another vertical bar (`|`).

so it probably came up before...

remark-lint has nothing to complain about this and remark-stringify is just wrong so that's fun.

**Review by cl8n — CHANGES_REQUESTED** [review]
pls split each kind of change into different PRs or at the very least different commits, I can't sanely review this when there are actual substantial fixes buried in 1000 lines of automated ones

also for the table spacing thing, it's probably better to leave them be and add relevant remark config instead. we should be able to use remark-stringify on the whole repo one day rather than addressing every minor formatting nitpick individually like this.

**Pull request merged**
