### PR TITLE
Add new PP/SR news post banners

### PR DESCRIPTION
**Pull request by Ephemeralis**
Designs courtesy of kaetwo. These should be used going forward, instead of the old (mode-agnostic) star rating image.

### CODE REVIEW

**Review by Walavouchey — CHANGES_REQUESTED** [review]
very against applying these retroactively. the posts have already been long published

**Comment by Ephemeralis** [comment]
The catch one is going to use them, so it seems strange not to use the others.

**Comment by peppy** [comment]
Should only be for new posts.

**Comment by Walavouchey** [comment]
if it feels awkward to use them only for the catch post so suddenly, then they could be put on hold until the next wave of changes

**Comment by Ephemeralis** [comment]
May as well only use them for the next batch, then.

**Comment by Walavouchey** [comment]
i suggest renaming to `pp-sr-{osu,taiko,catch,mania}.jpg`

- "banner" is redundant because of folder name
- "ctb" is an old term and "tko" uhhh

to my ears pp/sr sounds better than sr/pp and i believe the news post titles follow that order already

**Comment by Ephemeralis** [comment]
Swapped 'ctb' for 'fruits' and followed the naming schema above.

**Comment by peppy** [comment]
Is there a reason for "use non-minified assets"? The filesizes seem a touch exorbitant.

**Comment by Ephemeralis** [comment]
jpeg-recompress smallfry was introducing massive banding and artifacting on these banners, looks like jpegmini into imageoptim seems to be much better.

**Review by peppy — APPROVED** [review]

**Pull request merged**
