### PR TITLE
[KO] Add Game modifier

### PR DESCRIPTION
**Pull request by Ge-n-z**

### CODE REVIEW

**Comment by Ge-n-z** [comment]
well.. does anyone know how to fix this error?
[https://i.postimg.cc/J0gRVLss/dadasddasd.png](url)

**Comment by Nivalyx** [comment]
for the first error, it is caused by the double blank line on Line 61 and 62. simply removing either one of them should fix this.

image

for the second error, it's because how you write the square brackets (`[` and `]`) over Line 20 :

image

in Markdown, by default square brackets are used to indicate a link ([more on that here](https://www.markdownguide.org/basic-syntax/)) so if you're trying to write something in square brackets *that is not intended to be a link* you have to write it as `\[` and `\]`  instead. in this case, changing `['점수 배수']` to `\['점수 배수'\]` should fix the problem.

**Comment by Ge-n-z** [comment]
I really appreciate your comment. thanks <3

**Comment by TicClick** [comment]
merging (2+ weeks without a review from a native speaker)

**Review by TicClick — APPROVED** [review]

**Comment by TicClick** [comment]
sigh. I absolutely forgot I added this note on top: https://github.com/ppy/osu-wiki/blob/master/wiki/Game_modifier/en.md#L15
@Ge-n-z could you add this to the translation really quick, please?

**Comment by Ge-n-z** [comment]
wait a min

**Comment by Ge-n-z** [comment]
I'm not sure what I exactly have to do. So, I made 2 pull req. Check them :)

**Pull request merged**
