### PR TITLE
Fix one OWC 2021 match result

### PR DESCRIPTION
**Pull request by LevFlavien**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Review by TicClick — APPROVED** [review]

**Comment by cl8n** [comment]
well now the bold is wrong.
also I think the scores were already correct, just names in wrong order, since Chile is the higher seed

**Comment by TicClick** [comment]
why it is wrong? bold = winner's score, no?
and, according to both the linked match results, and the challonge bracket, France has won: https://challonge.com/OWC_2021

**Comment by cl8n** [comment]
the bold of the country name, i mean
and yes France won but the names are in wrong order, so the score was actually the correct thing and the name order was wrong

**Comment by ChillierPear** [comment]
MP link is displayed as France vs Chile so the page should follow convention. France won the match 6-5, as such their name should be highlighted alongside their score

**Comment by cl8n** [comment]
is the "convention" not that higher seed goes on left? I thought the whole point is that you can see upsets by finding bold names on the right. maybe I'm out of touch with how newer tournament articles go, but it seems weird to obscure that info

**Comment by Bazzadwarf** [comment]
> is the "convention" not that higher seed goes on left? I thought the whole point is that you can see upsets by finding bold names on the right. maybe I'm out of touch with how newer tournament articles go, but it seems weird to obscure that info

afaik there is no set way, I try to follow the bracket when possible so that most of the time higher seeds end up on the left and lower seeds on the right.

**Comment by LevFlavien** [comment]
oops

**Pull request merged**
