### PR TITLE
[ZH] Update `Ranking_Criteria`

### PR DESCRIPTION
**Pull request by YumeMuzi**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Review by RushFTK — DISMISSED** [review]

**Comment by TicClick** [comment]
@RushFTK @YumeMuzi I know it's been a while, but please also add the translation of https://github.com/ppy/osu-wiki/pull/7131/files -- I'll merge right after

**Comment by Walavouchey** [comment]
@RushFTK @YumeMuzi pinging once again. will otherwise just merge with an outdated marker

**Comment by RushFTK** [comment]
@Walavouchey @TicClick thx for mention, i will ask YumeMuzi for update.

**Comment by Walavouchey** [comment]
you can also add it as a suggestion yourself and we can apply it by ourselves

**Comment by YumeMuzi** [comment]
@TicClick sry for long periods of inactivity, I'll add #7131 later

**Review by RushFTK — APPROVED** [review]

**Review by Walavouchey — APPROVED** [review]

**Pull request merged**
