### PR TITLE
Update `History of osu! 2017`

### PR DESCRIPTION
**Pull request by MilkyIQ**
Part of #4871; rewrites and updates the History of osu! 2017 article.

### CODE REVIEW

**Comment by Ephemeralis** [comment]
briefly looked over this and am left wondering what kind of criteria you're using to determine what to write about, for example, you reference rich presence in halloween but completely skip over the contest (which was one of the most popular fanart contests ever held) and the medals that accompanied it, all of which are also referenced in the news post you source

the absolutely giant section about TD scores also needs to be cut way, WAY back, it's like a solid sixth of the entire article for one event

**Comment by Bazzadwarf** [comment]
I kinda agree with Eph's sentiment here. A lot of stuff happened during 2017, which should probably be mentioned, if at the very least, as a pointer to other articles in the wiki or the wider site. 

I'll go back through the archives and try and pull up some ideas, but if this is just a general cleanup, please let me know so I can put it somewhere else more appropriate.

**Comment by MilkyIQ** [comment]
> briefly looked over this and am left wondering what kind of criteria you're using to determine what to write about, for example, you reference rich presence in halloween but completely skip over the contest (which was one of the most popular fanart contests ever held) and the medals that accompanied it, all of which are also referenced in the news post you source

The general criteria I've been using to determine what to write about has been:
- New additions/changes (to osu! or website or whatever) (e.g., addition of a new mod or feature in osu!, big changes to the website, big changes like the merging of the chat mods and GMT, etc.)
- Any significant "firsts" (e.g., first mapping with rewards competition, launch of the osu!weekly newsposts, etc.)
- New additions to the osu!store (although this has been sort of inconsistent)
- Arguably "historical" (worth of note) community events (e.g., controversies like the freedomdiver score, or the big backlash from the difficulty spread rule change in 2016)

Up until now I've been following the precedent that for repeated events like fanart contests/tournaments/mapping contests/whatnot shouldn't be mentioned unless they're a first of their kind. (I've gotten to the point where I've just stopped looking into these events, which is why I didn't notice anything different with it). 

> the absolutely giant section about TD scores also needs to be cut way, WAY back, it's like a solid sixth of the entire article for one event

I realize now that I got too afraid of not giving due weight in that bit and ended up getting carried away. I'll start cutting the fat out of that section in my next commit.

> also if it's not obvious, you can poke me for details/stats on things and i can try to resolve stuff like how popular contests are, etc for these kinds of articles if it helps

If you have any other contests or such that you'd like to mention, please do tell. Will definitely start looking further into these in the future tho :+1:

**Comment by MilkyIQ** [comment]
> Ok, I have an initial rough draft of events and things that happened during 2017, I'm going to keep updating it as I find more stuff over the next few days, but any input is appreciated.
> ### [Github Gist](https://gist.github.com/Bazzadwarf/6457501859eadd7a991e08a9bd23510a)

Massive thank you for this @Bazzadwarf. I definitely intend on taking this and making changes to this article, its just that I've had essentially no free time due to personal reasons. I'm fine myself, I just don't have as much time as I used to.

P.S., if you're thinking about working on any HOO articles, just lmk on #4871. I'd love to see more work get put into that area

**Comment by Ephemeralis** [comment]
going to convert this to a draft for the meanwhile since a lot needs to be done still, may take a look at it myself in the interim as well

**Pull request closed without merging**
