### PR TITLE
[PT-BR] Update `Main Page`

### PR DESCRIPTION
**Pull request by GranularBow8193**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

`SKIP_WIKILINK_CHECK`

### CODE REVIEW

**Review by LeoFLT — DISMISSED** [review]
This needs a `SKIP_WIKILINK_CHECK` on the PR description, since the linked articles don't exist for PT-BR or the CI check will fail, looks good otherwise.

**Comment by GranularBow8193** [comment]
> This needs a `SKIP_WIKILINK_CHECK` on the PR description, since the linked articles don't exist for PT-BR or the CI check will fail, looks good otherwise.

Can you please explain it more precisely? I didn't get it what ou mean by a `SKIP_WIKILINK_CHECK`

**Comment by LeoFLT** [comment]
> > This needs a `SKIP_WIKILINK_CHECK` on the PR description, since the linked articles don't exist for PT-BR or the CI check will fail, looks good otherwise.
> 
> Can you please explain it more precisely? I didn't get it what ou mean by a `SKIP_WIKILINK_CHECK`

This article links to a page with an outdated translation, namely `[Storyboarding](/wiki/Storyboard#storyboarding)`, the storyboarding heading doesn't exist there, so the CI check fails. Putting a `SKIP_WIKILINK_CHECK` on the pull request's description ignores this check.

**Comment by GranularBow8193** [comment]
> > > This needs a `SKIP_WIKILINK_CHECK` on the PR description, since the linked articles don't exist for PT-BR or the CI check will fail, looks good otherwise.
> > 
> > 
> > Can you please explain it more precisely? I didn't get it what ou mean by a `SKIP_WIKILINK_CHECK`
> 
> This article links to a page with an outdated translation, namely `[Storyboarding](/wiki/Storyboard#storyboarding)`, the storyboarding heading doesn't exist there, so the CI check fails. Putting a `SKIP_WIKILINK_CHECK` on the pull request's description ignores this check.

and how I put this?

**Comment by LeoFLT** [comment]
> and how I put this?
By writing `SKIP_WIKILINK_CHECK` somewhere on the PR's description (the first comment, the one that has the Self-check section)

**Comment by GranularBow8193** [comment]
> By writing `SKIP_WIKILINK_CHECK` somewhere on the PR's description (the first comment, the one that has the Self-check section)

done, is now correct?

**Review by TicClick — APPROVED** [review]

**Pull request merged**
