### PR TITLE
Encourage a manual way to update changes from wiki

### PR DESCRIPTION
**Pull request by sr229**
While Upriver is a great service some advanced users might want to learn some new techniques as well. For that purpose, I documented a way to do so using git rebase

### CODE REVIEW

**Comment by Ephemeralis** [comment]
this is a good start, but the article would probably benefit from another section detailing the use of a git GUI tool like Git Extensions to make the process more palatable for people not use to CLI apps

**Comment by cl8n** [comment]
don't really understand why we'd encourage people to rebase like this. `git pull upstream master`?

**Comment by Ephemeralis** [comment]
i think to encourage fast-forward instead of having a billion merge commits fuzzing up the commit line? that's what tripped me up a lot when first using git

**Comment by cl8n** [comment]
`pull` (and the underlying `merge`) fast-forwards by default. if you're on master, you shouldn't be committing to it anyway so it'll always fast-forward. if you're on a branch that diverged from master (almost always means an open PR, for osu-wiki), you shouldn't overwrite history

**Comment by peppy** [comment]
I honestly think adding this kind of complexity is the wrong direction.

Maybe a guide on using the github desktop app would be useful? Or link to one, I'm sure github have that covered 10x over. There shouldn't be any need to rebase or do anything custom (also what @cl8n said – standard pull/merge should be preferred over rebase. if you rebase an already PR'd branch you risk rewriting history and force-pushing, which is something we'd want to avoid).

**Comment by Joehuu** [comment]
https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/syncing-a-fork (for CLI)

and/or

https://docs.github.com/en/free-pro-team@latest/desktop/contributing-and-collaborating-using-github-desktop/syncing-your-branch#merging-another-branch-into-your-project-branch (GitHub Desktop).

**Comment by sr229** [comment]
I'll redo everything to just point towards using the GitHub Desktop way. Though I accidentally deleted the branch associated with this so I'll just open a new one with updated changes.

**Comment by sr229** [comment]
> i think to encourage fast-forward instead of having a billion merge commits fuzzing up the commit line? that's what tripped me up a lot when first using git

This is the main reason, I was encouraging a more standardized and proven way to do fast-forwarding, while `git pull` works, `git rebase` is the recommended way.

**Comment by peppy** [comment]
the only useful time for fast-forwarding is before PRing, though.

**Comment by sr229** [comment]
Superseded by #4314

**Pull request closed without merging**
