### PR TITLE
[en] osu! store Typo fix: exteme->extreme

### PR DESCRIPTION
**Pull request by Gennadiyev**
Two errors changed.

### CODE REVIEW

**Comment by Gennadiyev** [comment]
Double checked, ready to merge.

**Comment by RaikireHiuduo** [comment]
Source: https://store.ppy.sh/store/product/2

exteme

:thinking: (It is impressive it took this long [I didn't notice at all until this PR]).

**Comment by Gennadiyev** [comment]
only error found, so only fix.

**Comment by Gennadiyev** [comment]
Another error found there, Chinese character 激&喝 are ? and ? in the file. Making changing now.

**Comment by Gennadiyev** [comment]
Done~

**Pull request merged**
