### PR TITLE
Credit the original forum designer, phill

### PR DESCRIPTION
**Pull request by TicClick**

### CODE REVIEW

**Comment by TicClick** [comment]
Russian version is reworked in #4610

**Comment by TicClick** [comment]
for what it's worth, the proof (not publicly accessible): https://osu.ppy.sh/community/forums/topics/1634

**Comment by peppy** [comment]
I'm trying to remember what part of the forums phill helped with, this is a memory that i've completely forgotten! (i'm sure it's accurate enough though; likely on the CSS side of things).

**Comment by TicClick** [comment]
it'd be awesome if you also knew who "Jim" is, since there is no profile link for them

**Comment by peppy** [comment]
Jim wasn't an osu! user, just a friend who offered me hosting for a brief period. If you want to delve deeper, he also helped out during the days when I ran a windows xp fan site..

**Comment by zeusminus** [comment]
While you're at it, could you also fix the listed role for Jim as well? It is supposed to be `Brave New Games`, not `Brand New Games`.

**Comment by peppy** [comment]
correct.

**Review by peppy — APPROVED** [review]

**Review by TPGPL — APPROVED** [review]

**Pull request merged**
