### PR TITLE
[ZH] Update `osu! copyright policy`

### PR DESCRIPTION
**Pull request by FlyingFish23**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [x] address cl8n's comment https://github.com/ppy/osu-wiki/pull/7612#issuecomment-1179481560

### CODE REVIEW

**Comment by Pisapou** [comment]
Just to make your title more readable (because there is a zh.md for every page of the wiki, your title don't indicate anything) try to follow this format : [LANG] Update/Add `Name of the file updated/added`

So for example here it would be : [ZH] Update `Legal/Copyright`

**Review by heipizhu4 — APPROVED** [review]

**Comment by FlyingFish23** [comment]
> Just to make your title more readable (because there is a zh.md for every page of the wiki, your title don't indicate anything) try to follow this format : [LANG] Update/Add `Name of the file updated/added`
> 
> So for example here it would be : [ZH] Update `Legal/Copyright`

Thanks for you advice! This is the first time I've done something like this so I kinda don't know the rules. I have experiences editing Wikipedia but I really haven't used GitHub to maintain a wiki page. I saw someone have changed the name, is there more things that I can do?

**Comment by heipizhu4** [comment]
> Is there more things that I can do?

1. Tick the checklist at the head of this PR.
2. Read the [github docs](https://docs.github.com/) for more github tips such as forks, branches and things like that.

**Comment by cl8n** [comment]
let's get this one up to speed with EN since it's so close; the parts that don't match rn are the last 2 paragraphs of "osu! copyright policy" and the last 2 paragraphs of "Submitting counter-notices"

**Review by kj415j45 — DISMISSED** [review]

**Comment by TPGPL** [comment]
converting into a draft, since the translation is still outdated and there has been no activity in months

**Comment by FlyingFish23** [comment]
> let's get this one up to speed with EN since it's so close; the parts that don't match rn are the last 2 paragraphs of "osu! copyright policy" (i.e. the first section) and the last 2 paragraphs of "Submitting counter-notices"

but i just checked and the last 2 paragraphs of submitting counter-notices are the same with the english version, the only difference with the current english version is the part about music licensing.

**Review by TPGPL — CHANGES_REQUESTED** [review]
- remove the `outdated_translation` mark
- L16 doesn't seem to be present in the English article, unless it's a sentence from L14 - if so, then those lines should be merged
- L18 uses an outdated formatting comparing to the English article
- L50 should be merged with L48 like in the English article
- missing `*Last updated 7 November 2019. [View history here](https://github.com/ppy/osu-wiki/commits/master/wiki/Legal/Copyright/en.md).*` line translation at the end (link shouldn't be changed)
- the informal address translation should be removed

**Comment by FlyingFish23** [comment]
> * remove the `outdated_translation` mark
> * L16 doesn't seem to be present in the English article, unless it's a sentence from L14 - if so, then those lines should be merged
> * L18 uses an outdated formatting comparing to the English article
> * L50 should be merged with L48 like in the English article
> * missing `*Last updated 7 November 2019. [View history here](https://github.com/ppy/osu-wiki/commits/master/wiki/Legal/Copyright/en.md).*` line translation at the end (link shouldn't be changed)
> * the informal address translation should be removed

outdated translation removed, merged L16 with L14, updated format for L18, L50 merged with L48, last updated time added and informal address translation removed.

**Review by TPGPL — APPROVED** [review]

**Pull request merged**
