### PR TITLE
Add exemption to spinner starts in rule about snapping

### PR DESCRIPTION
**Pull request by kitty-cloud**
for the partial version of this proposal accepted by naxess, which was discussed here: https://osu.ppy.sh/community/forums/topics/1214161

(first time making a PR, hope i'm doing it right)

### CODE REVIEW

**Comment by TicClick** [comment]
looks okay, but needs a look from NAT (@Naxesss?)/peppy

> RC change flow is as follows:
> 
> - New proposal is raised in the Ranking Criteria subforum on the forums.
> - The proposal is discussed until a consensus is met at the decision of the NAT with an obvious majority of support from all participants in the thread. No exact numbers are given. 
> - If the proposal is not contentious or has ongoing discussion present, it can then pass.
> - Once passed, a PR encoding the changes into the Ranking Criteria can be made by any member of the NAT (presumably the one involved in finalizing the decision).
> - The change is then discussed. peppy should be assigned to all RC PRs to sanity check them.
> - After a week or two with no further discussion (or after approval from peppy), the change can then be merged.

_Originally posted by @Ephemeralis in https://github.com/ppy/osu-wiki/issues/4722#issuecomment-761845070_

**Comment by Naxesss** [comment]
This will need other NAT to confirm that it's accessible enough before proceeding, as there are a few concerns:
- Changing order of objects in the .osu may be too technically demanding for the RC, which is aimed at even new mappers.
- It's (afaik) impossible to tell that the order of objects is wrong when looking purely in the editor.  As a result, this change may have a too high reliance on third-party map checking tools, e.g. Mapset Verifier, to follow/enforce reasonably.

Objects on the same tick is generally undefined behavior in standard. It may seem to work ok currently, but there's no guarantee things will stay that way. As such, you will also need to check with a dev (probably peppy, since he'll look at this anyway) to confirm that the change won't break anything.

**Comment by kitty-cloud** [comment]
>     * It's (afaik) impossible to tell that the order of objects is wrong when looking purely in the editor.  As a result, this change may have a too high reliance on third-party map checking tools, e.g. Mapset Verifier, to follow/enforce reasonably.

it's not, as explained by the linked lewski post; it's easy to tell by looking at the objects on the timeline

**Comment by peppy** [comment]
How is this any different?

**Comment by peppy** [comment]
Two hit circles should *not exist at the same time value*. The *only exception for this is mania*.

This may change in the future but is how it is for now. Please place the spinner *closer* but *not at the same millisecond value* as another hit object.

**Pull request closed without merging**
