### PR TITLE
Improve format of tournament match history notes

### PR DESCRIPTION
**Pull request by cl8n**
applied to owc 2023 as an example, but I think this is a better format than the numbered links thing for any future tournament. https://discord.com/channels/188630481301012481/218677502141399041/1167996377515708436

### CODE REVIEW

**Review by Walavouchey — CHANGES_REQUESTED** [review]
disagree. i don't think this is a proper solution, see https://github.com/ppy/osu-wiki/issues/8109

also we don't really use title texts on links anymore

**Comment by cl8n** [comment]
i agree with pretty much everything you said in that issue -- why do u disagree with this change then? im not really following

**Comment by Walavouchey** [comment]
i'd only agree if it's applied everywhere, but at that point i'd rather pick up the pace on resolving the linked issue (using icons instead)

**Comment by cl8n** [comment]
closing so the bot stops commenting on everything, but I still feel like at the very least this is better than `#1` etc... the number means nothing right now (with only a few exceptions)

#10354 also does a very similar thing, for reference

**Pull request closed without merging**
