### PR TITLE
Add entry for latest community meeting

### PR DESCRIPTION
**Pull request by peppy**
Not sure how this one should be listed, but best to get it visible on the page for those that are expecting to be able to access it from here.

### CODE REVIEW

**Comment by peppy** [comment]
@Ephemeralis not sure if you plan on summarising the meeting into some form of "meeting notes", but highlighting you in case that's going to happen. Not sure how important it is.

**Comment by Joehuu** [comment]
There's already a PR adding this: https://github.com/ppy/osu-wiki/pull/6906

**Comment by ZeroPyrozen** [comment]
There is on-going PR on #6906

**Comment by peppy** [comment]
The title of that PR meant that even after checking the PR I did not see it. Have you considered naming the PR using a standard english prose rather than including an underscored filename? I think it reads better.

Also the language prefixes are pretty ugly, labels would work much better but I guess they are there for people that can't adjust labels. For cases where the PR is updating every language it's not really necessary to include `[AA, AB, AAC, AD, AD, AF,AF, AG]` though, IMO.

**Pull request closed without merging**
