### PR TITLE
Update directory names for new article titles

### LINKED ISSUE #2580: Use sentence case for article titles and directory names
that'd make more sense since the other headers already do this

### PR DESCRIPTION
**Pull request by cl8n**
resolves #2580

- [x] https://github.com/ppy/osu-web/issues/5512
- [ ] update redirects
- [ ] update references
- [ ] make sure an admin is around when merging to re-index everything

this PR doesn't include Contests/ or Tournaments/ because they're all initialisms anyway. the changes were made via [program](https://github.com/cl8n/osu-wiki-bin/blob/master/sentence_case)

<details>
<summary>summary of changes</summary>

| Old path | New base path |
| :-- | :-- |
| People/The\_Team/Beatmap\_Nominators/Beatmap\_Veto | Beatmap\_veto |
| People/The\_Team/Beatmap\_Nominators/General\_Information | General\_information |
| Beatmap\_Editor/Beat\_Snap\_Divisor | Beat\_snap\_divisor |
| Beatmap\_Editor/Distance\_Snap | Distance\_snap |
| Beatmap\_Editor/Kiai\_Time | Kiai\_time |
| Beatmap\_Editor/SB\_Load | SB\_load |
| Beatmap\_Editor/Song\_Setup | Song\_setup |
| Beatmaps/Title\_Text | Title\_text |
| Guides/Adding\_Custom\_Hitsounds | How\_to\_add\_custom\_hitsounds |
| Guides/Audio\_Editing | Audio\_editing |
| Guides/Beginner's\_Tutorial | Tutorial\_for\_beginners |
| Guides/BSS\_Issues | How\_to\_resolve\_BSS\_issues |
| Guides/Changing\_the\_Artist\_or\_Title | How\_to\_change\_a\_maps\_artist\_or\_title |
| Guides/Collab\_Information | How\_to\_start\_a\_beatmap\_collaboration |
| Guides/Compressing\_Files | File\_compression |
| Guides/Cropping\_with\_Complex\_Backgrounds | How\_to\_crop\_images\_with\_complex\_backgrounds |
| Guides/Cropping\_with\_Simple\_Backgrounds | How\_to\_crop\_images\_with\_simple\_backgrounds |
| Guides/Custom\_Hitsound\_Library | Custom\_hitsound\_library |
| Guides/Custom\_Sample\_Overrides | Custom\_sample\_overrides |
| Guides/Getting\_Songs\_From\_Video\_Games | How\_to\_get\_songs\_from\_video\_games |
| Guides/Getting\_Your\_Map\_Modded | How\_to\_get\_your\_map\_modded |
| Guides/How\_to\_Play\_osu!mania | How\_to\_play\_osu!mania |
| Guides/How\_to\_Time\_Songs | How\_to\_time\_songs |
| Guides/How\_to\_Use\_the\_Offset\_Wizard | How\_to\_use\_the\_offset\_wizard |
| Guides/Live\_Streaming\_osu! | How\_to\_livestream\_osu! |
| Guides/Making\_Properly\_Centered\_Spinners | How\_to\_make\_properly\_centered\_spinners\_in\_skins |
| Guides/Music\_Theory | Music\_theory |
| Guides/OpenGL\_Support\_Issues | OpenGL\_support\_issues |
| Guides/osu!mania\_Mapping\_Guide | osu!mania\_mapping |
| Guides/Recording\_osu! | How\_to\_record\_videos\_of\_osu! |
| Guides/Searching\_and\_Downloading\_Beatmaps | How\_to\_search\_for\_and\_download\_beatmaps |
| Guides/Setting\_the\_Offset\_on\_the\_Correct\_Beat | How\_to\_set\_the\_offset\_on\_the\_correct\_beat |
| Guides/Starting\_a\_Beatmap\_Project | How\_to\_start\_a\_beatmap\_project |
| Guides/Tablet\_Purchase | Tablet\_purchase |
| Guides/Tips\_and\_Tricks\_on\_Skill\_Improvement | Tips\_and\_tricks\_on\_skill\_improvement |
| Guides/Videos\_From\_Youtube | How\_to\_download\_videos\_from\_YouTube |
| Help\_Centre/Account\_Restrictions | Account\_restrictions |
| Legal/Music\_Licensing | Music\_licensing |
| Mapping\_Techniques/Making\_Good\_Sliders | Making\_good\_sliders |
| Medals/Beatmap\_Packs\_0916 | Beatmap\_packs\_0916 |
| Options/Keyboard\_Bindings | Keyboard\_bindings |
| Options/Offset\_Wizard | Offset\_wizard |
| osu!\_File\_Formats/Db\_(file\_format) | db\_(file\_format) |
| osu!\_File\_Formats/Osb\_(file\_format) | osb\_(file\_format) |
| osu!\_File\_Formats/Osk\_(file\_format) | osk\_(file\_format) |
| osu!\_File\_Formats/Osr\_(file\_format) | osr\_(file\_format) |
| osu!\_File\_Formats/Osu\_(file\_format) | osu\_(file\_format) |
| osu!\_File\_Formats/Osz\_(file\_format) | osz\_(file\_format) |
| osu!\_Program\_Files/User\_Configuration\_File | User\_configuration\_file |
| osu!\_wiki\_Contribution\_Guide/Common\_Issues | Common\_issues |
| osu!\_wiki\_Contribution\_Guide/GitHub\_Web\_Interface | GitHub\_web\_interface |
| osu!stream/Song\_List | Song\_list |
| osu!tourney/Multiplayer\_Usage | Multiplayer\_usage |
| osu!tourney/Spectator\_Usage | Spectator\_usage |
| osu!tourney/Tournament\_Management\_Commands | Tournament\_management\_commands |
| Ranking\_Criteria/Difficulty\_Naming | Difficulty\_naming |
| Ranking\_Criteria/Skin\_Set\_List | Skin\_set\_list |
| Ranking\_Criteria/Timing\_Songs\_With\_8-Signatures | Timing\_songs\_with\_8-signatures |
| Reporting\_Bad\_Behaviour/Handling\_Foul\_Play | Handling\_foul\_play |
| Rules/Code\_of\_Conduct\_for\_Modding\_and\_Mapping | Code\_of\_conduct\_for\_modding\_and\_mapping |
| Rules/Song\_Content\_Rules | Song\_content\_rules |
| Rules/Visual\_Content\_Considerations | Visual\_content\_considerations |
| Skinning/Guides\_and\_Important\_Threads | Guides\_and\_important\_threads |
| Storyboard\_Scripting/Audio | Audio\_samples |
| Storyboard\_Scripting/Cheat\_Sheet | Cheat\_sheet |
| Storyboard\_Scripting/Compound\_Commands | Compound\_commands |
| Storyboard\_Scripting/General\_Rules | General\_rules |
| Storyboard\_Scripting/osu!\_File\_Toggles | osu\_file\_toggles |
| Article\_Styling\_Criteria | Article\_styling\_criteria |
| Beatmap\_Discussion | Beatmap\_discussion |
| Beatmap\_Editor | Beatmap\_editor |
| Chat\_Console | Chat\_console |
| Featured\_Artists | Featured\_artists |
| Game\_Modes | Game\_modes |
| Game\_Modifiers | Game\_modifiers |
| Help\_Centre | Help\_centre |
| Hit\_Objects | Hit\_objects |
| How\_You\_Can\_Help! | How\_you\_can\_help! |
| Mapping\_Techniques | Mapping\_techniques |
| News\_Styling\_Criteria | News\_styling\_criteria |
| osu!\_File\_Formats | osu!\_file\_formats |
| osu!\_Program\_Files | osu!\_program\_files |
| osu!\_wiki\_Contribution\_Guide | osu!\_wiki\_contribution\_guide |
| Performance\_Points | Performance\_points |
| Performance\_Troubleshooting | Performance\_troubleshooting |
| Play\_Styles | Play\_styles |
| Ranking\_Criteria | Ranking\_criteria |
| Reporting\_Bad\_Behaviour | Reporting\_bad\_behaviour |
| Skinning\_Tutorial | Skinning\_tutorial |
| Staff\_Log | Staff\_log |
| Storyboard\_Scripting | Storyboard\_scripting |
| Tournament\_Drawings | Tournament\_drawings |
| Visual\_Settings | Visual\_settings |
</details>

### CODE REVIEW

**Comment by cl8n** [comment]
should wait on https://github.com/ppy/osu-web/issues/5512 just in case

**Comment by cl8n** [comment]
splitting titles into a different PR that can merge before this one

**Comment by cl8n** [comment]
fixed according to other PR, now this one does nothing but rename files

**Comment by TicClick** [comment]
this is going to take a while (not to mention some articles were already renamed, so a new PR will be easier to merge), so closing for now. don't hesitate to reopen/make a new pull once you're back

**Pull request closed without merging**
