### PR TITLE
Use image figures and clean up formatting in Community Contributor news post

### PR DESCRIPTION
**Pull request by cl8n**
images parsed into figures will be centered by default, no need for the raw html

### CODE REVIEW

**Comment by bdach** [comment]
> images parsed into figures will be centered by default, no need for the raw html

...as long as they're the single image in a paragraph, I think ([source for claim](https://github.com/ppy/osu-web/blob/437e30252922b983e791abdf4265f60f8091268e/app/Libraries/Markdown/OsuMarkdownProcessor.php#L223-L225))

**Comment by cl8n** [comment]
yep, in this case they are alone in a paragraph

**Comment by cl8n** [comment]
@peppy ^probably a project setting to make it work as intended

**Comment by peppy** [comment]
Aha, I have enabled it now. Let's see how it goes.

**Pull request merged**
