### PR TITLE
Remove hyphen clarification on osu!taiko skinning files

### LINKED ISSUE #1892: Old info on Taiko skinning page
The hyphen doesn't seem to be anywhere, so it doesn't need to be left out
image

### PR DESCRIPTION
**Pull request by Joehuu**
Resolves #1892.

---

### CODE REVIEW

**Comment by TPGPL** [comment]
actually some of the animations with the hyphen dividing frame name and skin item name so i don't know if this change is needed

**Comment by Joehuu** [comment]
Reworded it, so it seems that the hyphen is used commonly to separate frame numbers.

Before, it was saying to omit something that is not there.

**Comment by Okorin** [comment]
dont think you need to clarify that it's not needed if the file is given in the format `filename{n}.png` to begin with - in fact clarifying makes this more confusing to read https://osu.ppy.sh/help/wiki/Ranking_Criteria/Skin_Set_List#osu!taiko doesnt clarify any of that either

**Comment by Joehuu** [comment]
Awaiting another opinion. Reverted back to removing them.

**Pull request merged**
