### PR TITLE
[ID] Add `Help_Centre/Installation_and_registration`

### PR DESCRIPTION
**Pull request by Nivalyx**
Indonesian translation of the `Help_Centre/Installation_and_registration` wiki page (http://osu.ppy.sh/wiki/en/Help_Centre/Installation_and_registration).

Also included a quick fix for an error in the English article that I found, where the download button on the main page was incorrectly referred to as `Download` instead of `Download now`.

image

---

edit : why did GitHub automatically sent a review request to both peppy and ephemeral out of the blue O_o

### CODE REVIEW

**Review by mousesalt — APPROVED** [review]
overall looks good on ID

**Review by TicClick — DISMISSED** [review]

**Review by TPGPL — DISMISSED** [review]

**Comment by TicClick** [comment]
> edit : why did GitHub automatically sent a review request to both peppy and ephemeral out of the blue O_o

your pull request affects files and/or directories that are protected and require a review from their owners: https://github.com/ppy/osu-wiki/blob/master/.github/CODEOWNERS. bundling them with a regular translation usually hides them and it's not always obvious that your PR needs an extra approval

**Review by TicClick — APPROVED** [review]
if anything, I've reverted the `Download now` change for _now_

**Comment by Nivalyx** [comment]
ah, i see 👍

**Pull request merged**
