### PR TITLE
Update team member lists and staff log

### PR DESCRIPTION
**Pull request by Blooshing**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by Blooshing** [comment]
hopefully my osu-wiki repo isnt broken like last time. 😭

**Review by cl8n — APPROVED** [review]
someone should review the ntoe I added to staff log, it's intended to be enough for anyone to update this without asking further questions

**Review by peppy — APPROVED** [review]
still think this is pretty silly to have to semi-manually update

**Comment by Blooshing** [comment]
> still think this is pretty silly to have to semi-manually update

Soon:tm: type of thing, I guess.

**Pull request merged**
