### PR TITLE
Add custom IDs to beatmap categories

### PR DESCRIPTION
**Pull request by Swekka**
Required for https://github.com/ppy/osu-web/pull/10722

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

SKIP_REMARK SKIP_WIKILINK_CHECK SKIP_OUTDATED_CHECK

### CODE REVIEW

**Comment by agatemosu** [comment]
why closed?

**Review by agatemosu — COMMENTED** [review]
lgtm

**Review by cl8n — APPROVED** [review]

**Review by cl8n — DISMISSED** [review]
@peppy please bypass ci for this one, I have confirmed it fixes everything it intended to and all the other errors are not new + out of scope

**Comment by Walavouchey** [comment]
(before fd63fa8d8879ea63ed00d303e067c767cd834c69)

`osu-wiki-tools check-links --all --outdated` 287 --> 347 errors compared to `master` before this branch
`osu-wiki-tools check-links --all` 61 --> 91 errors compared to `master` before this branch

was this change done manually? even though a10454c2350c38ee40f652ee714c7621527effca changes a lot of links it doesn't seem to be exhaustive

i assume @cl8n has checked that a10454c2350c38ee40f652ee714c7621527effca only changes link fragments

**Review by Walavouchey — DISMISSED** [review]

**Comment by Swekka** [comment]
I  missed some links

**Comment by Swekka** [comment]
> was this change done manually? even though [a10454c](https://github.com/ppy/osu-wiki/commit/a10454c2350c38ee40f652ee714c7621527effca) changes a lot of links it doesn't seem to be exhaustive

I forgot to change relative links, should be fine now.

**Comment by cl8n** [comment]
okay being complete works too then. I fixed what was remaining to get `osu-wiki-tools check-links --all` reporting no errors that target this article

**Review by cl8n — APPROVED** [review]

**Review by cl8n — APPROVED** [review]

**Pull request merged**
