### PR TITLE
Add `COE 2023 1v1 osu! Tournament` article

### PR DESCRIPTION
**Pull request by Walavouchey**
ignore branch name

no banner or staff listing yet, but this can be merged without those for now i think

- [x] TicClick: dummy edit to get task-list-complete running

the rules are almost identical to https://osu.ppy.sh/wiki/en/Tournaments/GTS/COEGTS_2023#ruleset

### CODE REVIEW

**Comment by peppy** [comment]
no mention of lazer?

**Comment by Walavouchey** [comment]
unfortunately no, i have not heard about any of the sort

**Comment by peppy** [comment]
It is running in lazer though. So it should be mentioned.

**Comment by Walavouchey** [comment]
i'll take your word for it

**Review by TicClick — APPROVED** [review]

**Pull request merged**
