### PR TITLE
Update: Multi (two table styles used [raw HTML, and GFM]).

### PR DESCRIPTION
**Pull request by RaikireHiuduo**
Change most tables to hardcoded HTML tables. Not yet refined. May need another check.

### CODE REVIEW

**Comment by TPGPL** [comment]
Actually we **shouldn't** use any HTML.

**Comment by Repflez** [comment]
Don't use HTML unless it's ***absolutely required.***

**Comment by RaikireHiuduo** [comment]
rowspan/colspan attribute, mainly.

Listing in the GFM Table need to be done with \<ul\> tags (which might end up unreadable the longer the list is). It can be done if you want to enforce GFM Table only.
Reference: https://stackoverflow.com/questions/19950648/how-to-write-lists-inside-a-markdown-table

On unrelated note: Yes, I am reading; just have no idea why I am not allowed to post. New to this (Pardon the pixelated image):-
discord

**Comment by RaikireHiuduo** [comment]
Push request.

Check Multi, and osu!academy (newly added) for changes.

**Pull request merged**
