### PR TITLE
Fix corner cases in blob size inspection

### PR DESCRIPTION
**Pull request by bdach**
As [seen](https://github.com/ppy/osu-wiki/runs/807554788) in #3760.

# Summary

There are two corner cases I forgot about when writing the blob size inspection, namely: files being moved and deleted. This PR is supposed to address both.

Excluding deleted files is easier and is done by specifying `--diff-filter=d` for `git diff`.

When it comes to moved files, `git diff --numstat` used the `{a -> b}` syntax to indicate moves which caused the inspection to catch fire. Thankfully there's a [documented](https://git-scm.com/docs/git-diff#_other_diff_formats), more machine-friendly format that uses `--numstat -z`. Unfortunately it requires more eldritch regexing.

Here's the explanation:

```
\-              first dash
\t              first tab
\-              second dash
\t              second tab
(               group for the old filename
    \x0         NUL byte
    [^\x0]+     anything but a NUL byte, 1 or more times - this is the old filename, *if* the file was moved
    \x0         NUL byte
)?              the old filename section is optional
\K              disregard everything seen up to now
[^\x0]+         anything but a NUL byte, 1 or more times - this is the current filename
(rest is left unmatched, but it's implied it'll be the final NUL byte and newline)
```

Due to the `NUL`s I also had to specify `--text` as `grep` thought it was looking at a blob itself.

This was tested on the following PRs:

| PR | before | after |
| :- | :-: | :-: |
| [case with moved blob](https://github.com/bdach/osu-wiki/pull/8) | ❌ ([execution log](https://github.com/bdach/osu-wiki/runs/808482633)) | :heavy_check_mark: ([execution log](https://github.com/bdach/osu-wiki/runs/808537875)) |
| [case with deleted blob](https://github.com/bdach/osu-wiki/pull/9) | ❌ ([execution log](https://github.com/bdach/osu-wiki/runs/808532206)) | :heavy_check_mark: ([execution log](https://github.com/bdach/osu-wiki/runs/808538325)) |

Note the proper filename in the first case and the lack of a file in the second.

### CODE REVIEW

**Comment by cl8n** [comment]
I don't think the capture group does anything, `-o` outputs the whole match. but it doesn't seem to matter because it's just a null byte that comes after it

**Comment by bdach** [comment]
Huh, you're correct. This is what I get for messing with regexes...

**Comment by cl8n** [comment]
apparently this was a less fun change than we thought because you can tell git to treat renames as add+delete

**Comment by bdach** [comment]
Sure, but then the delete would get ignored and the add would get checked, or is there some extra layer to it I'm not seeing?

**Comment by cl8n** [comment]
isn't that what we want? `--no-renames --diff-filter=d` leaves you with only the new filename as if it were added

**Comment by bdach** [comment]
Oh that's what it does. My bad for going off the option name and not reading docs, I just thought it nuked renames entirely, and not their detection.

**Pull request merged**
