### PR TITLE
[ES] Update `Main_Page`

### PR DESCRIPTION
**Pull request by agatem7**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

SKIP_WIKILINK_CHECK

### CODE REVIEW

**Comment by r0xANDt0l** [comment]
Native spanish speaker here (From Spain), The translations seems pretty good! It changed some stuff that was just some stuff literally translated to stuff that sounds more *spanish* to say it somehow

**Review by TPGPL — APPROVED** [review]

**Comment by agatem7** [comment]
There is a part that I forgot to translate

**Comment by agatem7** [comment]
In `Help`, there is a sentence that says `Profile restrictions` in French, but the language is Spanish.

**Comment by TPGPL** [comment]
@agatem7 if the translation needs fixing, you can open a new pull request with necessary changes

**Pull request merged**
