### PR TITLE
Beatmap Discussions: blind copy-paste the forum version

### PR DESCRIPTION
**Pull request by MegaApplePi**
### Description

- this one: <https://osu.ppy.sh/community/forums/topics/650961>

### Status

~~Pending~~ ~~WIP~~ pending review

### Changelog

- create en.md
- this one: <https://osu.ppy.sh/community/forums/topics/650961>
- convert images to jpg
- add some Markdown
- correct wording ("maps" -> "beatmaps" // "mapper" -> "creator")

### CODE REVIEW

**Comment by osuShiro** [comment]
Official name is Beatmap Discussions - make sure to replace every occurence of "modding v2" with this :P

**Comment by MegaApplePi** [comment]
Should the article be moved from `/wiki/Modding/v2` to `/wiki/Beatmap_Discussions` (with a redirect that points to there)?

**Comment by osuShiro** [comment]
Yeah. Ideally, we'd need to have people start using beatmap discussions instead of modding v2, but a redirect will be needed anyway

**Comment by MegaApplePi** [comment]
I am updating images to somewhat fit the ASC/Image standards (status Pending -> WIP)

**Pull request merged**
