### PR TITLE
[ES] Clean up `People/Nomination Assessment Team`

### PR DESCRIPTION
**Pull request by UnknownOsu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by agatemosu** [comment]
Could you update the list with osu-wiki-bin or remove the changes?

**Comment by UnknownOsu** [comment]
I don't think it should be translated, right? The program does, I just updated the roles in the list with the new values so the program will translate them automatically.

There was also new information to be added, so I did that.

**Comment by TicClick** [comment]
what's the status of the PR? @agatemosu would you be able to give it (at least) a quick review please?

**Review by TicClick — DISMISSED** [review]
merging (no native review for one week or longer)

**Review by TicClick — APPROVED** [review]

**Comment by agatemosu** [comment]
@TicClick #9149 was merged first xd

**Comment by TicClick** [comment]
oh thanks

**Pull request closed without merging**
