### PR TITLE
[ID] Add `Quality Assurance Team Blog` and update its English/French versions

### PR DESCRIPTION
**Pull request by Nivalyx**
Indonesian translation for the `Quality Assurance Team Blog` (http://osu.ppy.sh/wiki/en/Quality_Assurance_Team_Blog) wiki article.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Review by hikikuman — APPROVED** [review]
checked and safe.

**Review by ZeroPyrozen — DISMISSED** [review]
Looks good 👍 . Don't forget to include EN in title `[EN/ID]`

**Comment by TicClick** [comment]
@DoryanR should this be added to the French translation as well?

**Comment by DoryanR** [comment]
Yes, since it changes a lot of the sentence structure. This can be added in `fr.md` : 

L5: ```En septembre 2017, le blog de la QAT a été abandonné au profit de la série *QAT Gazette* qui a été publiée sur le [fil d'actualité](https://osu.ppy.sh/home/news). Tous les articles antérieurs du blog ont été portés rétroactivement sur osu!news par la suite.```

**Review by TicClick — APPROVED** [review]

**Pull request merged**
