### PR TITLE
Add custom ids to beatmap categories

### PR DESCRIPTION
**Pull request by Swekka**
Required for ppy/osu-web/pull/10722

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by agatemosu** [comment]
if this applies only to English, the pr of osu-web remains the same 🤷‍♀️

**Comment by Swekka** [comment]
That's true but I still think I probably shouldn't be editing articles of languages I don't speak. Let's wait for more opinions on this.

**Comment by TicClick** [comment]
your edits don't change the translations -- I see no issue with your first PR, https://github.com/ppy/osu-wiki/pull/10426
(if anything I'm surprised by how few links were broken even though I expected a lot of articles to lead to `Beatmap/Category`)

**Comment by Walavouchey** [comment]
> if anything I'm surprised by how few links were broken even though I expected a lot of articles to lead to `Beatmap/Category`

@TicClick well ci doesn't check unedited files

**Pull request closed without merging**
