### PR TITLE
[DA] Welcome

### PR DESCRIPTION
**Pull request by Pennek**
Completed translation of the 'Welcome' article to Danish.

### CODE REVIEW

**Comment by Pennek** [comment]
Goddamn, im too new to this. I screwed up force-pushing my branch. Any way for me to reopen this?

**Comment by cl8n** [comment]
from what I can tell it looks like you wanted to work on a different article alongside this one--- in that case you'll have to make different branches on your repo and PR them separately

I can reopen this one if you get `master` back to the right state, but opening a new one is fine too. message in #osu-wiki if u need help doing that

**Comment by Pennek** [comment]
ah thanks that makes sense! i'll get back working on it sometime tomorrow. who do i talk to to get write access on #osu-wiki ?

**Comment by cl8n** [comment]
in case you didn't see:

> [2:50 AM] clayton: can someone verify Pennek
> [3:13 AM] MillhioreF: have them put a proper message in arrival

read the #welcome channel first

**Pull request closed without merging**
