### PR TITLE
[DE] Add `Offset/Beatmap offset`, `Offset/Local offset` and `Offset/Online offset`

### PR DESCRIPTION
**Pull request by The-Last-Cookie**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by TicClick** [comment]
(apologies!)

**Comment by TicClick** [comment]
(also fingers crossed that `Beatmap offset` is going away -- https://github.com/ppy/osu-wiki/pull/8980)

**Comment by The-Last-Cookie** [comment]
Well, that is a pity. The needless work is within limits though luckily.

I think it is better to wait until everything has settled and #7254 is closed. Is there anything else planned for the offset articles, besides what is outlined in the issue?

Instead of adding the changes from #8981, I would like to mark the respective articles as outdated and update them, as soon as #7254 is finished.

Should I close this PR or is it okay to outdate them?

**Review by respektive — APPROVED** [review]
👍

**Review by TicClick — APPROVED** [review]

**Pull request merged**
