### PR TITLE
Clean up format of `Skinning/Sounds` and add Nightcore sample info

### PR DESCRIPTION
**Pull request by CloneWith**
This might be part of the solution of #2589 

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Review by Walavouchey — COMMENTED** [review]
- why are only some of these in tables? the ones which have additional information could have a "Notes" column for instance
- expand contractions ("aren't" --> "are not", etc.)
- "osu! client", "osu! cookie" instead of "osu!client" and "osu!cookie"
- the article should probably be renamed to something more grammatically correct than "Sounds skinning"

will check in more detail later

**Comment by CloneWith** [comment]
> why are only some of these in tables?
Some of sounds are similar in filename and usage, then I tried to merge them into one line, for example the hitsound sets and the `key-press-*` set.

> "osu! client", "osu! cookie" instead of "osu!client" and "osu!cookie"
> the article should probably be renamed to something more grammatically correct than "Sounds skinning"
Just kept them without changes when rewriting, will change later.

**Comment by cl8n** [comment]
I have very far down a todo list that I wanted to write about these files:
> nightcore-kick.wav
> nightcore-hat.wav
> nightcore-clap.wav
> nightcore-finish.wav

idk if I'll ever get to it but maybe it's relevant to do in this PR.

**Comment by CloneWith** [comment]
Have read osu! lazer source code and tried on stable by myself. It's really odd that I didn't find `nightcore-hat.wav` being used in stable (maybe?) but did in lazer, and the [corresponding wiki page](https://osu.ppy.sh/wiki/Nightcore)) seems unclear about this, not even mentioning it.

Don't know

**Comment by cl8n** [comment]
in stable
- the files are sourced from your skin, but not beatmap skin
- nightcore-hat plays only when slidertickrate is a multiple of 2
- nightcore-finish plays only when not omitting the first barline
- non-4/4 works differently, to be hoenst it's so confusing and these skin elements are so niche that I wouldn't even bother documenting non-4/4

otherwise it works same as lazer

**Review by cl8n — CHANGES_REQUESTED** [review]
rest of the changes seem fine, there's still a lot to improve about this article but the new layout here is certainly better

just fix NC and that's good for this PR

**Review by cl8n — APPROVED** [review]

**Pull request merged**
