### PR TITLE
External Ports to Similar Games

### PR DESCRIPTION
**Pull request by RaikireHiuduo**
### Description

Move External Ports to Similar Games.

### Status

Done.

### Notes

- `fr.md` Game Modes index page is broken for the external ports redirection
   - So does `Index`.
- Touches FAQ, Similar Games, Game Modes.
- Purges are a mistake.
- Also updated that osu!stream packs that cost money are now all costed and locked at 0.99USD.

### CODE REVIEW

**Comment by RaikireHiuduo** [comment]
_nothing really matters to meeeeeeeeeeeeeeeeeeeeeeee_

What to do now? Delete `osu!stream` and fix `Index`?

**Comment by sr229** [comment]
yes

**Comment by MegaApplePi** [comment]
no, keep `osu!stream`

ppy wrote:
image

you could fix `Index` but that probably should be done in another pull request

**Comment by sr229** [comment]
We should have a clear consensus on what to call this category, For instance, we won't call opsu! a "similar game" as it is a clone of osu! by nature.

**Comment by sr229** [comment]
CC @RaikireHiuduo for updates

**Comment by peppy** [comment]
I think "similar games" is fine. Another option would be "osu!-inspired games" i guess

**Comment by RaikireHiuduo** [comment]
Redirection drama I am gonna leave it to @MegaApplePi .

Not in scope for this PR.

Also, done for now. I seriously forgot what I should be fixing here other than similar games title is fine.

**Pull request closed without merging**
