### PR TITLE
Add Vietnamese for Bubbles

### PR DESCRIPTION
**Pull request by MineTurtlee**
Add: vi.md in /wiki/modding/bubbles
Made in **2 days**
(Inspired from "No Vietnamese version for this page" in wiki)

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)
- [ ] Everything good to go (Github Continous Integration).

### CODE REVIEW

**Review by MineTurtlee — COMMENTED** [review]
I think this is good to go.

**Comment by Walavouchey** [comment]
when translating articles, please copy the formatting of the english version exactly. github gave a lot of ci errors due to this.

you can easily ensure you get it right by literally copying the english article and translating while replacing the english parts. this way you can also ensure that links don't become incorrect since they'd be copy-pasted.

**Comment by MineTurtlee** [comment]
Okay but how can I fix "no blank**" thing?

**Comment by Walavouchey** [comment]
this is due to paragraphs not having spaces between them in your translation

incorrect:

```Markdown
## heading
- list
- list
paragraph
paragraph
```

correct:

```Markdown
## heading

- list
- list

paragraph

paragraph
```

please compare your version to the english one side-by-side.

**Comment by MineTurtlee** [comment]
Okay so I'm editing them now.
Thanks!

**Comment by MineTurtlee** [comment]
I'm not reopening this.

**Comment by peppy** [comment]
Is there a reason for closing this? Looked like it only needed minor spacing fixes.

**Comment by MineTurtlee** [comment]
Well I thought I can't edit anything at first, so I just closed it.

**Comment by agatemosu** [comment]
if you close a pr, the changes won't show up in the pr

**Pull request closed without merging**
