### PR TITLE
[ZH] [WIP] Article Style Guide

### PR DESCRIPTION
**Pull request by kj415j45**
Restart, continue #196

### CODE REVIEW

**Comment by kj415j45** [comment]
Please remove translations label, because zh-ASG is not only translation, and it contain some extend contents and remove en-only sections @TPGPL

**Comment by sr229** [comment]
can I get an update on this PR?

**Comment by kj415j45** [comment]
↑??? @TPGPL

**Comment by kj415j45** [comment]
sudden death, will continue in our group.

**Pull request closed without merging**
