### PR TITLE
Fix broken link in `Main_Page`

### PR DESCRIPTION
**Pull request by ZeroPyrozen**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by ZeroPyrozen** [comment]
I'm going to take a look on another translation files which haven't contained `osu! music licensing` article to make sure all link work

**Comment by peppy** [comment]
What's the point of this? Unless it's going to be applied using a script to the whole wiki (which I would run myself) this doesn't seem productive.

**Comment by ZeroPyrozen** [comment]
Can you check on this?

**Comment by peppy** [comment]
This is due to a missing redirect. No idea how this happened, someone has fucked up bad.

**Pull request closed without merging**
