### PR TITLE
Clarify CV formatting rule in RC

### PR DESCRIPTION
**Pull request by dorothy3242**
Minor wording fix to make it clearly allowed/required that if an anime character name is placed in the title field instead, i.e. `Title feat. Anime Girl` the same thing still applies.

### CODE REVIEW

**Comment by hypercyte** [comment]
would make it clear for this if anyone wants an example https://osu.ppy.sh/beatmapsets/1271261 :)

**Comment by cl8n** [comment]
"clearly allowed/required" seems like a stretch. I don't really understand this trend of making tiny technical wording changes to RC in hopes of clarifying a misunderstanding. why not just say it applies to title as well?

**Comment by dorothy3242** [comment]
It's not really a misunderstanding when RC specifically says to do one thing when people would in fact expect something else. Adding "oh applies to title too" sounds like even more of a bandaid.. updated PR with a slightly different version.

**Comment by cl8n** [comment]
updated version does solve my comment 👍

**Review by cl8n — APPROVED** [review]

**Pull request merged**
