### PR TITLE
[ZH/TOS]Quick format fixes

### PR DESCRIPTION
**Pull request by axmmisaka**
Got some little format error - offline syntax checker did not catch them.

### CODE REVIEW

**Comment by axmmisaka** [comment]
Don't know, but the original version has those.

**Comment by TPGPL** [comment]
i think you should delete that whitespace, as it's not needed 🤷‍♂️

**Comment by axmmisaka** [comment]
See if this is Okay

**Comment by TPGPL** [comment]
the numbers were okay, the whitespace like shown below isn't; check the diff

**Comment by axmmisaka** [comment]
Okay - I didn't get you in the first comment.
And yes - I will delete them in the next commit, but actually this is done on purpose, since they can be interpreted as 3 paragraphs and they will sqeeze together as in English version if there's no newline.

**Pull request merged**
