### PR TITLE
[PT-BR] Add `Bit rate`

### PR DESCRIPTION
**Pull request by flavin27**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by TicClick** [comment]
hi, I have cleared the second checkbox since I don't see a review from a Portuguese-speaking person. whether you are looking for one or not, let me know -- I'll either merge it in as-is with `no_native_review: true`, or wait until a native speaker approves your work

**Comment by flavin27** [comment]
well even thought I'm native speaker, I would like to wait for someone else's review. 
tbh I though there was someone who speaks Portuguese in ppy to be in charge for reviewing.

**Comment by TicClick** [comment]
not really, it's a free will model (whoever wants it, does a review)

**Review by TicClick — APPROVED** [review]
at this point there's been enough silence to warrant merge with `no_native_review: true`, which I'm doing right now

**Pull request merged**
