### PR TITLE
Mock language moderators

### PR DESCRIPTION
**Pull request by ImMock**
### Description

Updated Language_Moderators list in all languages.

### Status

Finished, Pending Review

### CODE REVIEW

**Comment by Repflez** [comment]
Your PR has several commits with non-descriptive messages.

Commit messages are used to learn about changes to a specific file/article without having to open the commit directly on GitHub or other tools used by contributors.

Please look into [changing your message to be more descriptive](https://help.github.com/articles/changing-a-commit-message/), you still have time to fix them.

**Comment by ImMock** [comment]
@Repflez I think its done now.

**Comment by MegaApplePi** [comment]
@ImMock there is a problem with your commits as Repflez had explained https://github.com/ppy/osu-wiki/pull/681#issuecomment-328317384.

**Comment by ImMock** [comment]
Even more descriptive?

**Comment by MegaApplePi** [comment]
Yes, they should be able to explain the changes to an article without having to look at the git diff. `Updated List` doesn't mean much, since we don't know which article was updated.

**Comment by kj415j45** [comment]
you'd better use another branch and squash them to the new branch and re-select this pr's head

**Comment by ImMock** [comment]
How can i do that? All of this is new for me.

**Comment by MegaApplePi** [comment]
I wrote this in like 10 minutes, but it should get the job done 🤞 

---

1. create a new branch, call it `Mock-Language_Moderators1` or whatever you want
image

2. create a pull request **under your fork**
image

3. Click this link so the two buttons looks like this
image

4. Change the "Compare:" to 
image

5. Change "Base fork" to your fork `ImMock/osu-wiki`
image

6. Change "Base" to `Mock-Language_Moderators1`
image

7. Click the green button
image

8. ignore the pull request box and click this green button
image

9. scroll down to the merge box, click on the dropdown (not the merge button, but the arrow next to it) and press `Squash and Merge`
image

10. Click that button
image

11. fix the title (this is the commit message)
12. fix the description
13. click that button
image

14. close this pull request
15. open a new pull requet
16. use `Mock-Language_Moderators1`

**Comment by ImMock** [comment]
@MegaApplePi I love you so much. <3

**Pull request closed without merging**
