### PR TITLE
Fix `TWC/2020` podium image

### PR DESCRIPTION
**Pull request by Ephemeralis**
The previous one was missing an 'i' in Horiiizon. I also flattened the image with smallfry.

### CODE REVIEW

**Review by TPGPL — APPROVED** [review]

**Comment by Walavouchey** [comment]
Brazil got 3rd, not the UK ?

Screenshot_20211210-155255

**Review by Walavouchey — CHANGES_REQUESTED** [review]
please check

**Review by TPGPL — DISMISSED** [review]
oh shit, right, its TWC 2020 podium banner 🤨

**Comment by Ephemeralis** [comment]
Force-pushed to fix it, should be correct now. Oops.

**Review by peppy — APPROVED** [review]

**Review by Walavouchey — APPROVED** [review]

**Pull request merged**
