### PR TITLE
[ES] Game mode/osu!mania

### PR DESCRIPTION
**Pull request by Lalo611**
Based on `en.md`.
Did not add articles/references.
Some variables were changed in the formula for better understanding in spanish.

### CODE REVIEW

**Comment by TPGPL** [comment]
your branch is outdated, the correct directory should be `wiki/Game_mode/...`

**Comment by Lalo611** [comment]
It is just the name of the branch? Should I make a new branch and then make the PR?

**Comment by zeusminus** [comment]
@Lalo611 you will need to pull the updates to your fork to keep up with the changes. You can make use of [Upriver](https://upriver.github.io/) for that matter.

**Comment by Lalo611** [comment]
Thanks!! I was searching about that!

**Pull request closed without merging**
