### PR TITLE
Update staff log and BN listing, use new flag style in "People" articles

### PR DESCRIPTION
**Pull request by Blooshing**
SKIP_OUTDATED_CHECK

### CODE REVIEW

**Comment by peppy** [comment]
Please provide the script / regex you ran to make these changes.

**Comment by Blooshing** [comment]
> Please provide the script / regex you ran to make these changes.

:pensive: I did this all with Ctrl+F `![][flag_<CountyCode>]` + replace function `::{ flag=<CountryCode> }::` Sorry to disppoint :pensive:

**Comment by peppy** [comment]
That makes it very hard to review. I'll just unsubscribe from this one. Seems pointless to have individuals makes these kind of sweeping changes to me, automate them if possible.

**Comment by cl8n** [comment]
this missed a lot of files and had some mistakes so I re-did the flags part and rebased on top of that. also re-did updating translations cuz the commit here hadn't localised anything (@Blooshing I think you need to update `osu-wiki`)

de0a4c13cf7daa9123bc78c371a7b42d789b56a5
```sh
find wiki/People -name '*.md' -exec sed -Ei \
-e 's/!\[\]\[flag_([A-Z_]{2})\]/::{ flag=\1 }::/g' \
-e 's/flag=__/flag=XX/g' \
{} +
```

12e125ee48dde779d74fd505d2250a2531a9eef1 - second set of expressions removes trailing newlines
```sh
find wiki/People -name '*.md' -exec sed -Ei \
-e '/^\[flag_[A-Z_]{2}\]:/d' \
-e ':a' -e '/^\n*$/{$d;N;ba' -e '}' \
{} +
```

**Pull request merged**
