### PR TITLE
[EN] Game mode / osu!mania | remove invalid link news page reference.

### PR DESCRIPTION
**Pull request by mousesalt**
[EN] [Game mode / osu!mania](https://osu.ppy.sh/wiki/en/Game_mode%2Fosu!mania) remove the link due to non-refer. add a new to woc2006's profile.

users with non-authorized can not access the page.

### CODE REVIEW

**Comment by peppy** [comment]
Probably best to actually leave the announcement reference there and refer to it, rather than removing it. Seems like something that could be useful to someone visiting this page and looking for more information to continue to.

**Comment by mousesalt** [comment]
that is a good idea, however, the link is referred to the forbidden page which the users may not access.
another way probably rewrites to a new link with same announcement article, so it can be updated and see by everyone.
image

**Comment by peppy** [comment]
Oh, that's a mistake. I'll move it somewhere it can be accessed again, give me a day or two.

**Comment by peppy** [comment]
I've fixed the issue. Sorry for the delay, phpbb is a pain to work with.

**Comment by TicClick** [comment]
closing this, as the whole announcements forum is publicly accessible now

**Pull request closed without merging**
