### PR TITLE
Revert "Amend DQ post rule"

### PR DESCRIPTION
**Pull request by TheMoMan**
Reverts ppy/osu-wiki#2276

There's been quite a bit of criticism about this rule change, the primary point being that it creates an environment that's too formal where a more casual setting is more appropriate for the community. This is also negatively affecting the motivation for the BNs and NAT doing this work.

I believe these concerns arose due to a combination of a lack of centralised discussion and being too hasty with applying this rule change.

So let's try this again, and I encourage anyone with an opinion to discuss here.

---

If this revert goes through, the NAT should be more strict in enforcing the old rule, i.e.:
- BNs **must clearly** state the reason for the DQ somewhere on the post, either on the first line or otherwise. There shouldn't be any misleading information about the reason for the DQ, nor should the reason be buried within a large wall of text. Basically have your fun, but at least keep the people who need to read the DQ info in mind.
- Just typing "dq on request" or posting just a screenshot of the mapper requesting the DQ would not be sufficient. This was the original intention for this rule existing.
- Do not post anything that would be removed under the community rules. I hope that this one is obvious, but just in case, here it is.

### CODE REVIEW

**Comment by FlyingStefan** [comment]
First of all I am shocked people are really adamant to want something that hilarious back. I understand people want their "fun" in what they are doing but come on: Are you defining fun by making yourself looking stupid? Feel free to do so but imo I'd like to see some more seriousness in the BNG where you can still have fun in what you are doing. Just do it the way where it is appropriate. And if you believe other people or I do a fuss about "a line" or "two" then you're not making it better with your reactions.

Now to the objective part: It's plain impractical having to read some random comment on an acutal important procedure for modding, especially when you cannot see the reason and/or have to bother checking the website for the reason because said BN cannot be bothered to post it in a visible way. If you want your stupid jokes to pop up in the post, let them be after the reason of DQ.

**Comment by pimpG** [comment]
what Stefan said.

so nowadays to get rid of what we don't like in the RC all we have to do is just being a bunch of crybabies?
they don't need to be in the BNG to have their "fun", there are many in-game channels and discord servers for that purpose even in official osu! discord servers, the ranking criteria is for general mapping assistance, not for encouraging/giving extra exposure for nonsense.

**Comment by Fantabulicious** [comment]
The rule itself is arbitrary and does not streamline or improve the nomination process in any perceptible way. I don't understand what about not wanting arbitrary restrictions makes anyone a "crybaby" as pimpG so eloquently put it.

Nominators who wish to follow this rule after it is reverted have nothing preventing them from doing so. However, I do not think "you look stupid," "anyone who pushed for this repeal is a crybaby," and "your fun isn't fun and your jokes are stupid" are useful defenses of the rule. If you would like more formality or seriousness in the BNG, perhaps start with yourselves - aggression and insults are not what I would describe as strictly useful, on-topic discussion.

Again, the rule is completely needless - any relevant parties who need to know the full reason for disqualification are not going to be getting it from a truncated one-line summary by a discord bot, and nobody likes to be bound by rules that fulfill no discernible purpose.

**Comment by FlyingStefan** [comment]
This has nothing to do with "aggression", it's brought to the point that silly nonsense where it's not necessary should be dimmed down. I'm not interested to dig into the thread because the BN is not capable to spend half of a second to type out the reason when they are supposed to do that, without anyone explictly telling them to do. Otherwise I'd rethink the choice of adding them at all if they do not consider to be productive and helpful to the audience.

There are the respective platforms to spread your memes, this here really shouldn't. And that we need to reroll this discussion is the epitome of comicality.

**Comment by UndeadCapulet** [comment]
this reversal is not being requested just because people wanna spread their memes and are salty it was taken away. i know as im the salty memer bitching about it the most.

the act of checking qualified sets is notoriously un-engaging for the vast majority of bn's and qat's/nat's that have been performing it, to the point that it has caused several massive system changes over like 4 years, the most recent of which was the change from qat to nat, which partially made it so nat wouldn't have to have qah activity anymore cuz they all hated doing it. its current design is innately dull, monotonous desk work with no incentives to perform it, aka the opposite of appealing for almost all bng.

which is why right now there are almost no active qah members, at least in standard, which is the gamemode that needs qah done the most since it sees the vast majority of qualified maps. there are like.. 3 consistently active qah tops from what i've seen? pimpg, venix, and flipping between me or someone else that happened to have motivation for a week. this is clearly not enough which is why many maps get ranked without any qah checks at all. the current dire situation has occurred repeatedly over the past year and will certainly happen again due to qah work's high turnover rate and lack of incentives.

if you want people doing qah work (which we do), at least one of 2 things needs to happen: it needs to be made enjoyable, or it needs to have some incentives. the latter is much less likely to happen and would require dev support to be integrated, which likelihood aside, would take a very long time to integrate and does not address the current lack of qah activity. the former is also difficult, cuz qah is innately boring, but there is a way from my experience that at least adds a tiny sliver of enjoyment to it: shitposting! is this a stupid thing to gain enjoyment from? yes! is it something that has seen an increase in qah activity? also yes!

addressing y'all's points:
"but memeing is unprofessional, dq's should be serious and clear"
bn work being super cereals is a really recent iteration of bn work, mostly caused by mv2, it was a much more casual environment back during the forum days. people shitposted for icons all the time and nobody minded. i really dont get the logic that bn work should be serious to begin with? this is a circle-clicking game, we do this cuz its fun, we should be able to have fun doing it. but the greater point is that making stuff super serious has been consistently shown to be a great way to get people to not want to do it. if you want to remove shitposting and make dqing a more professional thing then i highly encourage you to propose some alternative incentives that can be implemented. but killing shitposting should only be done after this.

"nobody forces you to do bn work! if you dont like it dont do it"
bn work is not qah work. bn work has alternative incentives already (m4ming with other bn's, ranking friends' maps, getting a sexy cool purple name, etc.). qah work does not have any incentives. taking the tiniest modicum of joy out of it is a great way to get people to not do it, which we have repeatedly seen over the years. except pimp i guess, but i think pimp is an outlier ^^' (which btw ty for all your hard work in qah pimp <3)

"its impractical to not see the dq reason in aiess/modding discussion dq line"
i think a shit ton of the recent dq's make it clear that this rule doesn't fix that at all, lol, those single lines almost never provide enough room for the dq reason, especially if there's a link to another post involved you get zero explanation without looking at the full post (which every party member involved does regardless). in fact i would argue the only thing that first line is good for is shitposting, cuz its almost never enough for a decent explanation.

did i miss anything? i feel like i missed something. whatever.

without incentives, proper qah activity will never be maintained on its own. we have a simple incentive we can provide. is it stupid? yes. but it's still an incentive, which is better than 0 incentives. until we have others, i would very much prefer we dont remove our only current one.

---
as far as the actual revert goes, i think we should drop the notion that "dq cuz <link>" or "dq on request" aren't enough. as i said, you have to view the post no matter what to actually understand the dq and almost always to even see the full reason, first line or not. "dq cuz <link" is the most direct (and dare i say, most professional?) way to get to the full reason.
and "dq on request"... like... that's literally the full reason? it's the mapper's map! who the fuck are you to ask why they want it dq'd? their reason doesn't matter, just dq it!

**Comment by ascendancelol** [comment]
i mean, it's not hard to just move memes to the second line. two seconds of mapfeed fame isn't really that important and honestly wasn't a problem until BNs got the DQ button. now that they have some semblance of responsibility, it becomes "oh it's a game" "it's the only thing that makes QAH enjoyable" etc etc, when QAH was fully functional before BNs had the DQ button. if you aren't enjoying being a QAH without a burning desire to shitpost then don't be a QAH, the incentive should simply be that you're helping your mode, which is what you (should have) signed up to do. either way, i'd much rather take a look at the future of the QAH, since that seems to be the problem, and has been i guess for a bit now.

that being said, being a BN doesn't have to be professional 100% of the time, but there's a time and a place for everything, and using the privileges you were granted by the QAT -> NAT change to shitpost is just not the right course of action in my eyes. there's plenty of discord servers, forum threads, and otherwise where that kind of stuff is okay, even in BN work. but we should be trying to keep things, especially dqs, as neat as possible. yes, that includes getting a reason for all dqs, even requested ones. reasons matter in things like evaluations where they're applicable, and if that information is not readily available, it causes problems.

just my opinion tho and if it gets reverted it's whatever to me, life goes on either way

**Comment by TheMoMan** [comment]
> as far as the actual revert goes, i think we should drop the notion that "dq cuz link" or "dq on request" aren't enough. as i said, you have to view the post no matter what to actually understand the dq and almost always to even see the full reason, first line or not. "dq cuz link" is the most direct (and dare i say, most professional?) way to get to the full reason.
> and "dq on request"... like... that's literally the full reason? it's the mapper's map! who the fuck are you to ask why they want it dq'd? their reason doesn't matter, just dq it!

"DQ because [link]" I can probably tolerate. It's not ideal but it's not the most inconvenient thing in the world.

As for "DQ on request", there's literally a myriad of reasons why they're asking for a DQ, and I don't think it's unreasonable to ask for that reason.  It's important so that people can track the changes made to the map easier without having to dig through the modding discussion for the reason (which may or may not even exist).

**Comment by pimpG** [comment]
Disqualifying maps is not part of QAH work, our focus is to check maps and Report the if we are concerned about something.
Even when only the qat were able to dq they still reported maps instead of dqing it themselves.

**Comment by pimpG** [comment]
Disqualifying maps is not part of QAH work, our focus is to check maps and Report if we are concerned about something.
Even when only the qat were able to dq they still reported maps instead of dqing it themselves.

**Comment by Mordredosu** [comment]
agree with uc

**Comment by naniface** [comment]
Hi, im left and came here to say sth

I didnt like 'professionalism' in this amateur game lol but can we say 'BN's basic attitude toward mapper'

https://osu.ppy.sh/beatmapsets/945049/discussion/-/generalAll#/1013183
I really like cool memes from BNs sometimes, and that making ranking process more funny. 
But you should know that when it comes to serious issue like iconing, DQing, mappers can feel bad since thats really really important one for them, and BNs making fun with that. And also mappers dont know which discussion was undergoing, so it can be seen as light decision to mappers.

Also pls consider that we not using english for main language (like korean like me), are suck at getting meme xd

Thanks for reading my shit english

**Comment by sr229** [comment]
Seriously I see no justifiable grounds for this merge, the rule itself is fine as-is. If you're mad about a QAT or BN being vague, feel free to complain to the staff and not vent it over here as a CL. This is childish and unprofessional by its own (which makes you a hypocrite).

I stand by my vote. Do not merge.

**Comment by pimpG** [comment]
as someone that's been a normal user for the most of my time spent in the game (8 of 9 years), i relate to what naniface/Left said.

making beatmaps can be very time consuming/tiring and pushing it for ranked is even harder.
i trully don't believe after all the trouble to try to rank a map people would be okay with BN's spitting on them just for a few moments of "fame".

Nominators are >voluntary< workers that are supposed to support the community, we are by no means "superstars" and we shouldn't be trying to act like we are superior to normal users. we are qualified for the task and we just chose to help. 

Makes zero sense to change the rule if it's just going to make reset tracking any less convenient.

**Comment by lassem22** [comment]
NAT member here, who unlike many of us still does a lot of bn activity, just so you know what this whole post is based on. 

Ever since modding v2 was forced on everyone the whole nomination process just kept on losing personality, which is what  ends up making it less enjoyable for a lot of the nominators.

Changes like this rule, while not major changes in themselves, keep adding up and drive more and more of the actually competent and active nominators out of the bng, or at least lower their motivation. 
This is not since they are "suddenly not allowed to shitpost anymore", but because the whole process feels less and less personal each passing day. 

The cost of this rule and similar changes (lower motivation for a lot of bns) vastly outweights the benefit (more "professionality" in something people do for enjoyment, and thus the rule change should be reverted.

I'd also advice people that aren't in touch with the modding to give this a read https://twitter.com/u896613/status/1152348318665781250?s=19 (text and comments to the tweet) as it might help their understanding of such situations. It's very hard to actually judge impact of such changes without being in a position that is actually effected by it. 

Forcing more professionality in bn activities is one of the contributing factors to the loss of personality in these, which in turn drives more and more active and competent nominators away from the bng and/or gets them burnt out much easier.

As long as dq posts contain the reason in the posts, it shouldn't really matter what people start their post with.

**Comment by cl8n** [comment]
forcing professionalism is the wrong way to go, but I don't see how this particular rule contributes to that. I think it's just more about convenience, because if I'm any random user wondering why a map got DQ'd, I don't want the first reason I see to be an inside joke that I don't understand

I like the direction you're pushing for, but I don't think this case has anything to do with it. we should figure out other ways to make modding more fun/engaging/personal

**Comment by lassem22** [comment]
the reason is still supposed to be clearly visible in the dq post itself, so what you mentioned about people not being able to easily see the reason from looking at the dq won't be an issue

**Comment by cl8n** [comment]
I didn't say it's hard to see the reason if you're looking at the dq post. it's hard to see the reason if you're looking at any of the places where only one line can fit (which are the most clear & visible usually), and the poster didn't include important information on the first line. if there weren't a problem, this rule wouldn't exist

this thread makes it sound like a way bigger deal than it is, which is why I think all of this talk about motivation, making modding more fun, etc. is hardly relevant here. surely we can come up with better ideas than "let people misuse a convenient feature" to achieve those goals

**Comment by pishifat** [comment]
last paragraph in cl8n's latest comment sums up my thoughts. this rule should be evaluated for what it is, not for how it relates to BN interest in checking qualified maps. incentives for doing that need work in other ways that wouldn't be solved by reverting this, so it'd make sense to shift efforts towards that

**Comment by Mordredosu** [comment]
it's about being allowed to have any sort of fun, not being allowed to shitpost a little with mapfeed just removes yet another fun thing you were able to do, modding v2 already leaves barely any room for anything fun

bns are doing everything for free, there is literally no reward at all other than some badge that you get after 2 years of keeping minimal activity, taking away more and more things is just gonna make the people that actually care quit (funny thing is literally talked with an ex-bn about this yesterday who said he quit because of modding v2)

once again, as long as the reason for the reset is **clearly visible within the post** there shouldn't be any room for complaint, I highly doubt anyone clicking the mapfeed links has a pc so bad that loading the webpage takes 10 minutes; on top of that, going only by mapfeed links would implicate that no one doublechecks anything, what if I were to dq a map and link a completely unrelated issue instead of the actual reason? Since nat is supposed to doublecheck this ANYWAYS they'd have to open the page regardless of what's written in the first line, if they don't they're not doing their job properly

oh and "keeping up a professional attitude" seems like a big meme to me when we have devs like ephemeral posting stuff like https://i.imgur.com/mjCRfTe.png (I don't mean to put him in a bad light at all, just using this as an example), I'm sure people won't suddenly quit the game because someone didn't put the dq reason in the first line :D 

what I would be fine with personally is not shitposting resets if you don't know the mapper, if you talk to or even are friends with them this shouldn't be an issue at all

**Comment by cl8n** [comment]
> Since nat is supposed to doublecheck this ANYWAYS they'd have to open the page regardless of what's written in the first line

it's not meant to give NAT/BN the full details, it's for anyone else just looking to get some quick insight. a good analogy (that has been mentioned in another conversation, I've been told) is how only the first line of a git commit message is shown here on GitHub, and it's a great convenience for no extra effort, provided the committer doesn't write something meaningless on the first line

> if you talk to or even are friends with them this shouldn't be an issue at all

when you post on modding discussions, especially on the part that is pinned for easy access, you're speaking to not only the mapper but other modders and community members wondering why the map was DQ'd. making jokes with the mapper here just confuses people and makes this feature useless, unless if your joke is something that everyone will understand (which you shouldn't assume)

other stuff is already discussed further in previous comments

**Comment by Mordredosu** [comment]
I can guarantee you anyone with half a brain cell will be able to find the reason right away if I format my post something like this 


"[insert meme here]

dq'd for X issue"


whoever can't see it like that shouldn't be using a computer in the first place, I don't consider the community to be this dumb and I'm pretty sure you don't think so either, you keep talking like everyone will suddenly write a wall of text and bury the reason somewhere inbetween when that hasn't happened like... ever? people playing this game aren't 5 years old

I *highly* doubt the average user will be confused because there are 2 lines of text instead of 1, please stop acting like this is the case

**Comment by cl8n** [comment]
we're talking about these previews


and related previews on external sites/bots/whatever. if you write enough not-actual-reason at the start of the dq post, then it becomes a useless message. the post itself is not problematic when viewed fully

**Comment by Mordredosu** [comment]
if it's not problematic when viewed fully where is the issue? no one uses the history tab for that and nearly no one only goes by the preview below the nomination status. oh and btw both of them have a link to the post that you can click, just saying

**Comment by cl8n** [comment]
> if it's not problematic when viewed fully where is the issue?

when viewed partially. previews exist for convenience

:/ I don't know how to respond to your main concern further without repeating myself, so here is a repeat of myself:
> this thread makes it sound like a way bigger deal than it is, which is why I think all of this talk about motivation, making modding more fun, etc. is hardly relevant here. surely we can come up with better ideas than "let people misuse a small convenience feature" to achieve those goals

**Comment by qcl12345** [comment]
> if it's not problematic when viewed fully where is the issue? no one uses the history tab for that and nearly no one only goes by the preview below the nomination status. oh and btw both of them have a link to the post that you can click, just saying

The issue is that it _is_ problematic when viewing the preview. You are ignoring the actual issue because it is a non-issue somewhere else.

I personally use the history tab quite often to get the gist of events on a particular mapset. And once https://github.com/ppy/osu-web/issues/3686 is fixed/implemented these previews will be even more useful. You shouldn't be forced to click a link and be brought to an _entirely different page_, not just tab, to understand what the DQ is for.

**Comment by TheMoMan** [comment]
I agree with the notion that reverting this rule doesn't really solve the impersonal problems with modding discussions. These problems should be solved by changing modding discussion themselves rather than changing rules and using the system in unintended ways.

**Pull request closed without merging**
