### PR TITLE
[ZH] Fix typo in the translation word `Beatmaps`

### PR DESCRIPTION
**Pull request by Kotoki1337**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

## Note

The typo in `Help_Centre/Account` has been mentioned/fixed in #8976.

### CODE REVIEW

**Review by TicClick — DISMISSED** [review]

**Comment by TicClick** [comment]
your feature branch has fallen quite behind the current `master`, so I resolved 3 conflicts -- please make sure to recheck the diff and verify that it matches your intent

**Review by YumeMuzi — CHANGES_REQUESTED** [review]
把那些暗病修了吧，以前的wiki是 `_xxxxx_` 来作斜体，现在应该使用 `*xxxxx*`

**Comment by TicClick** [comment]
> 把那些暗病修了吧，以前的wiki是 `_xxxxx_` 来作斜体，现在应该使用 `*xxxxx*`

it's an unrelated failure -- best to exclude the newspost from the PR instead of trying to fix existing style errors (I'll get to them sometime later)

**Review by TicClick — APPROVED** [review]

**Comment by TicClick** [comment]
you can merge it at your discretion now

**Pull request merged**
