### PR TITLE
Move judgement-related images to `/wiki/shared/judgement`; update images in `Gameplay/Judgement/osu!catch`

### PR DESCRIPTION
**Pull request by TicClick**
part of #6431

## Self-check

- [x] add the `catch-banana.png` sprite to `Gameplay/Judgement/osu!catch/img/`

### CODE REVIEW

**Comment by ZeroPyrozen** [comment]
`fruit-bananas`
alt text

**Comment by Walavouchey** [comment]
why not put these in `wiki/shared/judgement/osu!catch/` just like the other ones?

image

**Comment by TicClick** [comment]
they are not shared between the articles. furthermore, as osu!catch has no judgement wrt hit timing, these are still replicas of the pictures from the results screen, albeit of higher quality

**Comment by Walavouchey** [comment]
i guess

**Review by Walavouchey — APPROVED** [review]

**Pull request merged**
