### PR TITLE
Update CGTS 2021 to Regional Finals

### PR DESCRIPTION
**Pull request by fajar13k**
- Add each region's Semifinals match results
- Add each region's Finals mappool

### CODE REVIEW

**Review by TicClick — APPROVED** [review]
why are there so many commits when you can fit this into a single one?

**Comment by fajar13k** [comment]
> 
> 
> why are there so many commits when you can fit this into a single one?

It's the best practice I learn and use from my workpalce, so the habit's going here too. ;-;

**Comment by TicClick** [comment]
to me, the best practice is that two separate commits include two logically separated sets of changes -- I can hardly imagine, for example, the EU mappool being submitted but the NA one rolled back; if things are at the point of being 100% correct and finalized, _I personally_ see no point in splitting them.

on the other hand, it's harmless for osu! wiki anyway

**Comment by fajar13k** [comment]
> to me, the best practice is that two separate commits include two logically separated sets of changes -- I can hardly imagine, for example, the EU mappool being submitted but the NA one rolled back; if things are at the point of being 100% correct and finalized, _I personally_ see no point in splitting them.
> 
> on the other hand, it's harmless for osu! wiki anyway

Will short it to 2 commits in the next update. (pools and results) ✨

**Pull request merged**
