### PR TITLE
[ES] Add `Circle_size`

### PR DESCRIPTION
**Pull request by Ekkusu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by Ekkusu** [comment]
now i noticed a mistake but i'm not sure.
In the part of tags, should I also translate them or leave them like that? Well, I would suppose yes, although I can't find that regulation.... (not sure)

**Comment by TPGPL** [comment]
English tags shouldn't be removed, but you can add the translations for them as separate tags (it's not mandatory though)

**Comment by Ekkusu** [comment]
Thank you~, I already fixed it, also I changed a mistranslated term

**Review by TicClick — APPROVED** [review]
merging (no native review after 2+ weeks)

**Pull request merged**
