### PR TITLE
[KO] Update osu!taiko ranking criteria

### PR DESCRIPTION
**Pull request by SanjeninNagi**
Change Muzukashii Rule Kor Translate 
little size

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by SanjeninNagi** [comment]
re-check plz

**Comment by Walavouchey** [comment]
there's no need to continually update the branch yourself. a maintainer will do this for you before the pr gets merged

**Comment by libneko** [comment]
It would be enough to remove the outdated markers in lines 1 to 5, I think. Others... seems fine, since there's no substantial change except for the 146th line.

**Review by Walavouchey — APPROVED** [review]
i'll take that as an approval

**Pull request merged**
