### PR TITLE
[FR] Beatmap_Editor Folder

### PR DESCRIPTION
**Pull request by DoryanR**
This Pull Request contains the most recent version of these pages : 

- AiMod
- Beat Snap Divisor (Update)
- Compose 
- Design (Update)
- Kiai Time (Update)
- Menu
- SB Load
- Song Setup (Update)
- Timelines 
- Timing (Update)

For the sake of clarity I gathered all the other PRs done before, seeing that there are too many PRs for a single folder.

So I am closing my other PRs (#3034, #3032, #3031, #3030, #3028, #3027, #3026, #3025, #3024, #3023) and bringing them all together here.

### CODE REVIEW

**Comment by TPGPL** [comment]
i highly recommend doing "1 translated article = 1 PR" as making such a big PR is annoying/uneffective to review and hard to merge then

**Comment by almaloste** [comment]
Big PR with 1 mistake/line is really annoying

**Comment by DoryanR** [comment]
> i highly recommend doing "1 translated article = 1 PR" as making such a big PR is annoying/uneffective to review and hard to merge then

And I thought it was better... I don't know how I can go back to the way it was before because I've already merged everything together and taken out the individual branches...

**Comment by DoryanR** [comment]
> Big PR with 1 mistake/line is really annoying

So that's really overkill...

I'm taking my time to do this, when I could be doing a lot of other things more important than translating content for a game, being criticized like that, it really makes me not want to continue.

There's not one line that's a mistake at all, it's an outright lie based on nothing but air.

Before you say anything, please think about what you're saying, it would be better for everyone (by the way, I know you're French, and you know better than me that there aren't that many mistakes).

**Comment by DoryanR** [comment]
Obviously I seem to have a problem with some people here, and since these people are part of the French translators, they're going to deliberately not revise translations, so I'm going to let them figure it out, because I spend hours and hours doing these translations, and if it's for nothing, I'd rather not do anything at all, so figure it out.

**Comment by bdach** [comment]
In my opinion I think you might be unnecessarily ascribing malice to the other French translators. Objectively speaking the volume and speed at which you've been submitting translation PRs would make it hard to review for volunteers on their own in any language, and if it is true that they require almost as much work fixing up as they do when reviewing (which I can't form an opinion on), then I'd say they have a justifiable reason to not do so.

In the PR workflow the main focus is _getting things merged_, not submitting so much work that everyone has to play catch-up.

**Pull request closed without merging**
