### PR TITLE
Add 2007-2013 staff logs

### PR DESCRIPTION
**Pull request by pishifat**
nobody wanted this but here it is

### CODE REVIEW

**Comment by cl8n** [comment]
\> does the work of god
\> "nobody wanted this"

**Comment by cl8n** [comment]
deleted account infos

```markdown
[strager](https://osu.ppy.sh/users/64678)
[TouhouNerd](https://osu.ppy.sh/users/396056)
```

**Comment by TicClick** [comment]
super impressive, thank you very much. may also be of interest to @Ephemeralis

**Comment by peppy** [comment]
this completes me

**Comment by Ephemeralis** [comment]
my god he's done it

re: strager, i anecdotally remember him being deleted after he pissed peppy off one too many times for messing with things he shouldn't have, this was well before the era of even account bans

**Review by Ephemeralis — APPROVED** [review]

**Pull request merged**
