### PR TITLE
Update NAT member listing and mark internal representatives

### PR DESCRIPTION
**Pull request by momoyosu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by cl8n** [comment]
I'm not sure where you got the commit listed in 8ec5e7406aa35de188bde66ec055c3dbd8717f1e, it's (generally) supposed to the first one in your PR

**Review by cl8n — APPROVED** [review]

**Comment by ennchata** [comment]
i just ctrl-v’ed to him what the ci tool was saying but that’s a good thing to know ty

**Comment by cl8n** [comment]
that's not what CI said either though :thinking: where did you find that?

**Comment by ennchata** [comment]
oh nevermind i did give him the right commit @momoyosu don’t mess with what the ci checks tell you to do!!!

**Pull request merged**
