### PR TITLE
Update difficulty spectrum

### PR DESCRIPTION
**Pull request by mcendu**

### CODE REVIEW

**Comment by ZeroPyrozen** [comment]
Can you also update [Star rating](https://github.com/ppy/osu-wiki/blob/master/wiki/Beatmapping/Star_rating/en.md) article image?

**Comment by TicClick** [comment]
I may be wrong, but osu! wiki may not support SVGs

**Comment by gagahpangeran** [comment]
Now I check osu-framework doesn't support load svg, see https://github.com/ppy/osu-framework/issues/1956

So for now this image can't be displayed in osu!(lazer) wiki page.

**Comment by mcendu** [comment]
> Now I check osu-framework doesn't support load svg, see [ppy/osu-framework#1956](https://github.com/ppy/osu-framework/issues/1956)
> 
> So for now this image can't be displayed in osu!(lazer) wiki page.

Also I used `@font-face` with `data:` URLs instead of converting the text to path for ease of editing and translation, which could complicate things.

**Comment by peppy** [comment]
Please use PNG.

**Comment by mcendu** [comment]
Should I still keep the SVG (used to generate the PNG) in case we need another update or for translations?

**Comment by peppy** [comment]
I'd say that should be in figma, not in an svg. But I'm 100% certain @arflyte is not updating that. So let's keep the svg here as a reference.

**Comment by peppy** [comment]
You CANNOT embed the torus font. It is a commercial font and that goes against its licence.

Please rebase / force push to avoid committing it to this repository.

**Comment by mcendu** [comment]
Switching to Exo 2.

**Comment by peppy** [comment]
No. Don't embed any fonts.

**Comment by peppy** [comment]
If you need fonts then just nuke the svg from this repo.

**Review by peppy — APPROVED** [review]

**Pull request merged**
