### PR TITLE
Add LastExceed to `Users with unique titles`

### PR DESCRIPTION
**Pull request by ZeroPyrozen**
## Summary

Add notable osu!mania Fade In player and contributor of Fade In and Hidden implementation on osu!lazer ppy/osu#9538

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] Get confirmation from @WalterToro and @Ephemeralis

### CODE REVIEW

**Comment by cl8n** [comment]
pretty sure this is more of a gameplay-related one, they're one of the only ppl that consistently play FI at high level

hopefully someone can confirm exactly when/why the title was given though.

**Comment by peppy** [comment]
cc @Ephemeralis

**Comment by Walavouchey** [comment]
if the lazer contributions were the reason for the title, then it should be listed below `Contributors` imo

**Comment by peppy** [comment]
If you just need to know whether it's gameplay related then yes, it is.

**Comment by ZeroPyrozen** [comment]
> If you just need to know whether it's gameplay related then yes, it is.

Is there any explanation about what LastExceed achieved to get this title? Like "Have the highest osu!mania performance point count which all played with Fade In mod as of ${dateTitleIssued}"

**Comment by Ephemeralis** [comment]
The todo note (notable fade-in/hidden player & implemented fade-in in osu!lazer) about covers it. The dude is bonkers.

**Review by Ephemeralis — APPROVED** [review]

**Pull request merged**
