### PR TITLE
Add linting rule for wiki links

### PR DESCRIPTION
**Pull request by MegaApplePi**

### CODE REVIEW

**Review by cl8n — CHANGES_REQUESTED** [review]
made pr to u, also why is it excluded from news?

**Comment by MegaApplePi** [comment]
I merged the PR.

I thought that news didn't really care about the wiki link formatting.

**Comment by cl8n** [comment]
might as well enforce it since there's no downside. idk why it wasn't already

**Review by cl8n — APPROVED** [review]
good check, thanks

**Pull request merged**
