### PR TITLE
[ES] Translation update `People`

### PR DESCRIPTION
**Pull request by UnknownOsu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by agatemosu** [comment]
could you close this PR? for what it puts in the bot message

**Comment by UnknownOsu** [comment]
Are you sure? There are some untranslated ones in yours

**Comment by agatemosu** [comment]
I did it on purpose

**Comment by UnknownOsu** [comment]
Ye, I know, but wouldn't it be better to translate it than to leave it in English?

**Comment by TicClick** [comment]
closing in favour of https://github.com/ppy/osu-wiki/pull/9051, if you have any issues with the translation, please make a follow-up PR with respective edits

**Pull request closed without merging**
