### PR TITLE
[ID] Update `Reporting_bad_behaviour/Abuse`

### PR DESCRIPTION
**Pull request by Nivalyx**
- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by Nivalyx** [comment]
> Your translation may be missing new information from corresponding English articles. Please update your translation according to the merged changes:
> 
>     * [Fix grammar in `Reporting Abuse` #11460](https://github.com/ppy/osu-wiki/pull/11460), files:
>       
>       * [`wiki/Reporting_bad_behaviour/Abuse/en.md`](https://github.com/ppy/osu-wiki/pull/11460/files#diff-dff98a9c83438498ef238819a8a49da9f8fc404e97263e2dcf567fc2babf5027)

this warning can be safely be ignored ig, since #11460 changes nothing to the article except for a minor grammar improvement on a single sentence

**Comment by Nivalyx** [comment]
^ can be ignored as well

> Your translation may be missing new information from corresponding English articles. Please update your translation according to the merged changes:
> 
>     * [Fix English title and remove outdated mark in translation of `Reporting bad behaviour/Abuse` #11462](https://github.com/ppy/osu-wiki/pull/11462), files:
>       
>       * [`wiki/Reporting_bad_behaviour/Abuse/en.md`](https://github.com/ppy/osu-wiki/pull/11462/files#diff-dff98a9c83438498ef238819a8a49da9f8fc404e97263e2dcf567fc2babf5027)

**Comment by cl8n** [comment]
this is missing the changes up to L41 in https://osu.wiki/status/diff/5f603d93877d6b915ce864a793df5f4a7fbc2a33/wiki/Reporting_bad_behaviour/Abuse/en.md

also, remove outdated tag

**Review by cl8n — CHANGES_REQUESTED** [review]
^

**Comment by Nivalyx** [comment]
oh i nearly forgot about this ;~;

@cl8n i think i get everything fixed, can you please give this one a check again soon?

**Comment by cl8n** [comment]
still seems missing a line after new L31

> To do so, click the `Report post` button in the top right corner of the forum post.

**Comment by Nivalyx** [comment]
whoops, should be added now @cl8n

**Review by cl8n — APPROVED** [review]

**Comment by cl8n** [comment]
sry that took forever

**Pull request merged**
