### PR TITLE
Add fixes to Accuracy, Showcases, Best Of, Mascots/Gallery, Multi (Markdown)

### PR DESCRIPTION
**Pull request by TPGPL**

### CODE REVIEW

**Comment by MegaApplePi** [comment]
the image `/wiki/Mascots/Gallery/img/CtB_Menu.png` (on this pull request) exists when `/wiki/Game_Modes/osu!catch/img/CtB_logo.jpg` (on `master`) already exists

**Comment by TPGPL** [comment]
@MegaApplePi so should i move it to shared?

**Comment by MegaApplePi** [comment]
yeah

**Comment by TPGPL** [comment]
Fixed

**Pull request merged**
