### PR TITLE
Reorganise many articles according to #6080

### PR DESCRIPTION
**Pull request by Gamingzone123**
start to move stuff around towards #6080 

there is no Storyboarding\Specifications\Concepts\Coordinate_space for `osu!_pixel` to be linked to

waiting on:

- #7270 
- #7442

depends on:

- (separate) <s>the timing article being rewritten/amalgamated from `Timing_section` and Client\Beatmap_editor\Timing</s>
- (separate) <s>discussion of where to put offset articles</s>

I also don't get how:

- (separate) <s>the current `Touhosu` article can be merged into the `April_fools` article as they seem completely separate from one another</s>
- (Fixed) <s>CI is getting an issue with a pipe and I'm not sure how to fix this</s>

- [x] add redirects in `redirect.yaml`

### CODE REVIEW

**Comment by Walavouchey** [comment]
Because the branch [wasn't up to date](https://osu.ppy.sh/wiki/en/osu%21_wiki/Contribution_guide/Best_practices#syncing-the-fork) when you started making changes, there are tons of merge conflicts

image

It'll be way easier to redo these moves on a new branch than to resolve all of the conflicts. I'd also recommend waiting before https://github.com/ppy/osu-wiki/pull/7181 is merged

**Comment by Walavouchey** [comment]
nvm was able to update the branch via rebase pretty easily

**Comment by DoryanR** [comment]
I have looked at where the articles have been moved according to the list present in the PR quoted, and everything seems to be in order, except for two articles:

- `Local_song_offset` which should go in `Beatmapping/Timing/`
- `Online_offset` which should also go in `Beatmapping/Timing/`

Otherwise nothing to say, it's a good job.

**Comment by Walavouchey** [comment]
> - `Local_song_offset` which should go in `Beatmapping/Timing/`
> - `Online_offset` which should also go in `Beatmapping/Timing/`

we still haven't decided where to put them, see [discussion on discord](https://discord.com/channels/188630481301012481/218677502141399041/964863600655212604)

**Comment by TicClick** [comment]
adding a note on why this isn't merged yet:

> [8:55 AM] Walavouchey: again, i'm waiting on the link checker to be updated (#7288). it'll make checking for any issues way easier
> https://discord.com/channels/188630481301012481/218677502141399041/968762217812074557
>[9:01 AM] Walavouchey: secondly, merging before #7270 would make it receive a lot of conflicts that would be harder to resolve than updating #7187, which is way easier

([via](https://discord.com/channels/188630481301012481/218677502141399041/972753601694949406))

**Comment by Walavouchey** [comment]
ci checks pass, but the total broken link count shoots up from 288 (current master) to 657 (this branch)

from looking at the errors, it seems that some redirects haven't been added due to ci not giving errors for them. it seems we'll need to turn on link checking for all articles sooner than later

upon closer inspection of the moves here, it seems some of them aren't in the task list in https://github.com/ppy/osu-wiki/issues/6080. will take some time to sort it out

**Comment by Walavouchey** [comment]
the total error count is now at 278. the remaining ones are link fragment issues and a few reference link errors, which can probably later be fixed automatically by comparing heading levels and counts, at least in up-to-date articles

i've checked the moves now and updated the task list in the linked issue - should be all good now

**Review by Walavouchey — APPROVED** [review]

**Review by TicClick — CHANGES_REQUESTED** [review]
the majority of moves looks good to me, except that everything that is related to sliders should be in `Gameplay/Hit_object/Slider/` instead of being standalone articles in `Gameplay/Hit_object/`

**Comment by Walavouchey** [comment]
done

**Review by TicClick — APPROVED** [review]

**Pull request merged**
