### PR TITLE
Add back part about not italicising "osu!" in `Brand identity guidelines`

### PR DESCRIPTION
**Pull request by Walavouchey**
apparently wasn't carried over in https://github.com/ppy/osu-wiki/commit/0ebae0f44e20451d3ab15d218745dd27e6091844 (@TicClick?)

### CODE REVIEW

**Review by TicClick — APPROVED** [review]
I found it redundant, because in https://osu.ppy.sh/wiki/en/Article_styling_criteria/Formatting#italics we have:

> Names of work or video games should be italicised. osu! — the game — is exempt from this.

**Comment by Walavouchey** [comment]
has been a thing for a while now (https://github.com/ppy/osu-wiki/commit/6280f7070760bdf7179fbf4ec8596976e649f376#diff-985a993ead0467ab901560789dc6753cd9726ea3bc98e893c50068db093d669cR424) so i'm pretty sure it should be in there

**Comment by Nivalyx** [comment]
in id.md : 

change `"osu!" selaku nama permainan tidak boleh ditulis dengan diawali oleh huruf besar.` to `"osu!" selaku nama permainan tidak boleh ditulis dengan huruf besar atau huruf yang dicetak miring.`

**Comment by The-Last-Cookie** [comment]
de.md:

```diff
diff --git a/wiki/Brand_identity_guidelines/de.md b/wiki/Brand_identity_guidelines/de.md
index de185bfeac..d39e7a6525 100644
--- a/wiki/Brand_identity_guidelines/de.md
+++ b/wiki/Brand_identity_guidelines/de.md
@@ -10,7 +10,7 @@ Die Richtlinien zur Markenidentität sind ein Standard zur Markenbildung von osu

 ## osu!

-Der Name des Spiels, osu!, darf nicht großgeschrieben werden. Die offiziellen osu!-Marken dürfen keine Leerzeichen enthalten:
+Der Name des Spiels, osu!, darf weder groß noch kursiv geschrieben werden. Die offiziellen osu!-Marken dürfen keine Leerzeichen enthalten:

 - Spielmodi: `osu!`, `osu!catch`, `osu!taiko`, `osu!mania`
 - Projekte: `osu!academy`, `osu!talk`
```

**Comment by agatemosu** [comment]
In Spanish:

```diff
-El nombre del juego, osu!, no debe escribirse con mayúscula. La marca oficial de osu! no debe utilizar ningún espacio:
+El nombre del juego, osu!, no debe escribirse con mayúscula o en cursiva. La marca oficial de osu! no debe utilizar ningún espacio:
```

**Comment by Repflez** [comment]
es.md:

```diff
-El nombre del juego, osu!, no debe escribirse con mayúscula. La marca oficial de osu! no debe utilizar ningún espacio:
+El nombre del juego, osu!, no debe escribirse con mayúscula ni en cursiva. La marca oficial de osu! no debe utilizar ningún espacio:
```

Although @agatemosu beat me already, I still left my possible translation.

**Review by peppy — APPROVED** [review]

**Pull request merged**
