### PR TITLE
Minor fixes to the mods page

### PR DESCRIPTION
**Pull request by Shadowtail117**
Namely, some grammar fixes and a fix on the game modes not showing properly on the subtitles on the Relax section.

### CODE REVIEW

**Comment by oralekin** [comment]
Why not fix the HTML images while you're at it?

**Comment by Shadowtail117** [comment]
Alright, I'll work on that. Hope to fix the images by tomorrow night (~20-22 hours from now).

**Comment by MegaApplePi** [comment]
#238 is working on the images for Game Modifiers already. :/

**Comment by Shadowtail117** [comment]
Oh, RIP. Well, I just finished, to you can take it if you want.

**Comment by MegaApplePi** [comment]
I mean, we'll take your grammar fix suggestions, but there was already another pr that was most of that page already.

**Comment by Shadowtail117** [comment]
Okay, I have started a pull request from my fork to Supermind's (https://github.com/EpicSupermind/osu-wiki/pull/2) so the collaborations can be combined. If it succeeds, then there you go; this pull request is no longer needed.

**Pull request closed without merging**
