### PR TITLE
Update beatmap status list in the Interface article

### PR DESCRIPTION
**Pull request by mikser572**
Added "loved" to searching by ranking status. Marked all the translations as outdated.

---

### CODE REVIEW

**Comment by TPGPL** [comment]
better add it to every translation instead of marking as outdated, doesnt require language knowledge i think

**Comment by mikser572** [comment]
I mean, I can do it, but they're gonna still be outdated. Images don't really work and translations contain almost half of the lines of the original article.

**Comment by TPGPL** [comment]
then let's leave them outdated 🤷‍♂️

**Comment by Joehuu** [comment]
Can do it here too. https://github.com/ppy/osu-wiki/pull/1818/files#diff-6d0672fc5036826c3f110250d3cb17c4R128

**Pull request merged**
