### PR TITLE
Update en.md

### PR DESCRIPTION
**Pull request by Ge-n-z**

### CODE REVIEW

**Comment by timi137137** [comment]
emmm，maybe don't change "tags"

**Comment by Ge-n-z** [comment]
Done

**Comment by timi137137** [comment]
i see ,is good

**Comment by TicClick** [comment]
your changes look like you want to replace the English version with its Korean translation. what did you want to do instead here?

**Comment by Ge-n-z** [comment]
Actually I don't know about GitHub's system. So I clicked every button, tried everything that I could do. If it had something wrong, I apologize.

**Comment by TicClick** [comment]
it's okay, I just don't understand what you wanted to do initially. if it was in response to my comment in https://github.com/ppy/osu-wiki/pull/4689#issuecomment-764513068, I wanted you to replace `*[모딩](/wiki/Modding)과 혼동하지 말아주세요.*` with a Korean translation of `*For other uses, see [Mod (disambiguation)](/wiki/Disambiguation/Mod).*`

**Comment by TicClick** [comment]
and for that, you'd go to https://github.com/ppy/osu-wiki/blob/master/wiki/Game_modifier/ko.md (since it's already submitted) and make an edit using the pencil icon on the right -- please open a new pull request for that

**Comment by Ge-n-z** [comment]
I just wake up. Your request is done now

**Comment by Joehuu** [comment]
Superseded by https://github.com/ppy/osu-wiki/pull/4829.

**Pull request closed without merging**
