### PR TITLE
[FR] Create `osu!stream`

### PR DESCRIPTION
**Pull request by geshii**
Still WIP. I just already create the PR so people know that there's no need to translate it from scratch

### CODE REVIEW

**Comment by DoryanR** [comment]
Personally I would have avoided to translate this article, because according to the TODO in the first line, it must be updated.

**Comment by geshii** [comment]
> 
> 
> Personally I would have avoided to translate this article, because according to the TODO in the first line, it must be updated.

We can also try to update it tho

**Comment by DoryanR** [comment]
@geshii I think for the moment we can close the PR, waiting for either an update of the article in English from you, or from someone else.

**Comment by geshii** [comment]
> @geshii I think for the moment we can close the PR, waiting for either an update of the article in English from you, or from someone else.

It's already a draft, why closing it ?

**Comment by TPGPL** [comment]
are there any plans to finish this PR?

**Comment by TPGPL** [comment]
I'm going to close this PR for now if there are no plans to finish it; feel free to reopen it when you are ready

**Pull request closed without merging**
