### PR TITLE
Keep Beatmap_Spotlights up to date

### PR DESCRIPTION
**Pull request by TTTaevas**
Note that for some reason, the Winter 2021 season lacks image files (badges) with names finishing by "_3", at least compared to Summer & Autumn 2020. Due to that, I chose to let the pages show the Autumn badges rather than the Winter ones.

### CODE REVIEW

**Comment by venix12** [comment]
the removal of ``_3`` badges is intentional, they are not a thing anymore

**Comment by Nivalyx** [comment]
a lot of things in the pt-br locale seems to be outdated tho. for example the playlists for each season [have long been moved to a separate article to avoid congestion](http://osu.ppy.sh/wiki/en/Beatmap_Spotlights/Seasons) and quite a good bunch of other stuffs seems to have either been or deleted, reworded, or moved elsewhere :

image

image

i think rather than updating/fixing the pt-br article it would be wiser to simply add an "outdated" tag into it tho, so that it can be properly fixed up later by a native speaker in a future pr...

**Comment by TTTaevas** [comment]
Alright, then I can update which badges the pages should show, with the exception of the Brazilian page.
Do you think I should revert pt-br.md back to its original state, so a native speaker can fully take care of updating it?

**Comment by Nivalyx** [comment]
i believe so, yeah

**Comment by TTTaevas** [comment]
Unless I'm mistaking, pt-br already features the "outdated" marker:
Screenshot_2021-02-05 ppy osu-wiki

**Comment by Nivalyx** [comment]
ah, yeah, i think you are right 👀

i think everything should be good to go except for the one missing space between `当前赛季为` and `2021` in the zh.md :

image

**Review by Nivalyx — APPROVED** [review]
looks good on my end

**Comment by peppy** [comment]
Should previous seasons not be listed on the page as well? Or are we happy to throw out the historical context?

**Comment by Nivalyx** [comment]
hmm, i'm not the one who writes the current English article but iirc the documentation of all the seasons (both previous and current) are also on the wiki tho albeit on a slightly different page (http://osu.ppy.sh/wiki/en/Beatmap_Spotlights/Seasons) :

image

image

((as written above this is presumably done to avoid putting too many information in the main Beatmap Spotlights article))

**Comment by TTTaevas** [comment]
#4699 had created a conflict, a96d186 should resolve it. My bad for the commit's name

**Comment by peppy** [comment]
I see. No worries then.

**Review by TicClick — COMMENTED** [review]
not sure why this is not merged yet -- apologies

**Review by TicClick — APPROVED** [review]

**Pull request merged**
