### PR TITLE
Add new editions of `o!RST` Tournament

### PR DESCRIPTION
**Pull request by NiceAesth**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] Double check rules for 2022 and 2023 editions
- [x] Double check staff list for 2023 edition

### CODE REVIEW

**Comment by NiceAesth** [comment]
Ok, this PR is going to be reviewed by @Teetoos98 again on sunday. If you have other PRs to review in the meantime you can let this one be until then @TicClick

**Comment by NiceAesth** [comment]
CI is failing due to a completely unrelated file.

**Review by TicClick — APPROVED** [review]
all good -- wish I could have reviewed it sooner

**Comment by NiceAesth** [comment]
No worries, thanks for the review! Sorry the PR was massive.

**Pull request merged**
