### PR TITLE
[ZH] Add `Kudosu`

### PR DESCRIPTION
**Pull request by Asiimoviet**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by TicClick** [comment]
please only check the second checkbox (review from a native) if there has been a review from other person posted on GitHub, which there isn't

**Comment by Asiimoviet** [comment]
> please only check the second checkbox (review from a native) if there has been a review from other person posted on GitHub, which there isn't

alr sry bout that. how can i find a native reviewer?

**Comment by TicClick** [comment]
you have three options:
1) ask your friends
2) ask in #osu-wiki of the osu!dev Discord server
3) check who has reviewed other PRs in your language and ask them either in osu! or here by @mentioning them: https://github.com/ppy/osu-wiki/pulls?q=is%3Apr+is%3Amerged+%5BZH%5D+

alternatively, you can wait for 14 days and your PR will be merged regardless, only with a note that it wasn't reviewed

**Comment by Asiimoviet** [comment]
> you have three options:
> 
> 1. ask your friends
> 2. ask in #osu-wiki of the osu!dev Discord server
> 3. check who has reviewed other PRs in your language and ask them either in osu! or here by @mentioning them: https://github.com/ppy/osu-wiki/pulls?q=is%3Apr+is%3Amerged+%5BZH%5D+
> 
> alternatively, you can wait for 14 days and your PR will be merged regardless, only with a note that it wasn't reviewed

okay. btw i joined the dev server like 2 days ago and i sent an intro in the arrival channel. still no hearing now. so i can't send things in the osu-wiki channel.

**Comment by Asiimoviet** [comment]
@TPGPL Hi, can you help review my PR?

**Comment by TicClick** [comment]
I'm afraid he doesn't know the language. look for the users that have left comments in Chinese or authored such PRs (for example @YumeMuzi)

**Comment by Asiimoviet** [comment]
I showed my friend who is a native speaker. Will that suffice?
image

**Comment by Asiimoviet** [comment]
> 注意在中英与数字之间应添加一个空格，规范方面可以参阅[这篇文章](https://osu.ppy.sh/wiki/zh/Article_styling_criteria)

ok

**Review by TicClick — APPROVED** [review]

**Pull request merged**
