### PR TITLE
Reword osu!mania difficulties drain time restriction

### LINKED ISSUE #2109: Mania ranking critera rephrase because of new difficulty icons
So with the new icon changes a part of the ranking criteria that affects mania has become very confusing. Speceficly here "...lower than 3:30, the lowest difficulty of each included game mode cannot be harder than a Normal. Because osu!mania does not have a difficulty-specific Ranking Criteria yet, an osu!mania beatmapset's Normal difficulty is defined as a difficulty below 2.00 stars." The reason this is confusing is because mania's normal icon is no longer below 2 stars, and with the new icons that is an easy.
My suggestion for a quick fix would be to rephrase the whole sentence to "...lower than 3:30, the lowest difficulty of each included game mode (except osu!mania) cannot be harder than a Normal. Because osu!mania does not have a difficulty-specific Ranking Criteria yet, an osu!mania beatmapset's lowest difficulty must be an easy difficulty."

### PR DESCRIPTION
**Pull request by Joehuu**
Fixes #2109.

---

### CODE REVIEW

**Comment by cl8n** [comment]
this doesn't help because "Easy" is left undefined (there is no osu!mania-specific RC)

I think the issue is invalid anyway because "2.00 stars" isn't meant to refer to a difficulty icon, it's just an arbitrary star rating that was chosen. RC difficulties don't have much to do with the icons on the website

**Comment by Joehuu** [comment]
I thought it was defined in https://osu.ppy.sh/help/wiki/Difficulties#star-rating with the general star rating ranges for every mode.

The issue author probably knew that `Easy` now fits into that arbitrary range. /shrug

**Comment by cl8n** [comment]
that article seems really misleading, I'm not sure why it references RC at all

the characteristics of each difficulty should be defined under the "Difficulty-specific" header of each game mode's RC article (which I believe they are for all except osu!mania)

**Comment by Joehuu** [comment]
https://github.com/ppy/osu-wiki/pull/2102#discussion_r261884894

**Comment by cl8n** [comment]
that was a step in the right direction but I think that sentence can be removed altogether

**Comment by Joehuu** [comment]
Guess I'll close then.

**Pull request closed without merging**
