### PR TITLE
[IT] Update `Installation`

### PR DESCRIPTION
**Pull request by marcostudios**
Hopefully I didn't forget anything, i have glasses for a reason

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Review by agatemosu — COMMENTED** [review]
- put [IT] Update \`Installation` as the title of the pr
- line 59 is outdated
- remove the first 3 lines of the file
- and this:

**Comment by agatemosu** [comment]
on line 55, instead of putting "if it's not open", put "and click the osu!direct button on the right side of the main screen."

**Review by Sclafus — DISMISSED** [review]

**Comment by Sclafus** [comment]
The italian part looks good for me, not sure if everything has been upgraded tho.

**Review by Sclafus — APPROVED** [review]
LGTM

**Review by TicClick — APPROVED** [review]

**Pull request merged**
