### PR TITLE
Cleanup `Global Moderation Team` team listings

### PR DESCRIPTION
**Pull request by aceticke**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

This has been in the blame for 5 months and I only just noticed.

SKIP_OUTDATED_CHECK

### CODE REVIEW

**Comment by aceticke** [comment]
Don't merge yet

**Comment by aceticke** [comment]
Seems okay now?

**Comment by UnknownOsu** [comment]
In #10762, in the list of all gmt members (i guess also in the list of the respective moderating language), [Lyawi](https://osu.ppy.sh/users/5851253) was not listed. It may or may not have been a mistake, I'm just letting you know in case it was a mistake and can be fixed in this pull request

**Comment by aceticke** [comment]
> In #10762, in the list of all gmt members (i guess also in the list of the respective moderating language), [Lyawi](https://osu.ppy.sh/users/5851253) was not listed. It may or may not have been a mistake, I'm just letting you know in case it was a mistake and can be fixed in this pull request

I wasn't the one who added Lyawi, but after checking it does seem to be a mistake, so I'll go ahead and fix it.

**Review by Walavouchey — APPROVED** [review]

**Pull request merged**
