### PR TITLE
[JA] Update `Modding`

### PR DESCRIPTION
**Pull request by yuzupon1133**
- Corrected grammar in translation.
- Corrected typographical errors.

## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by yuzupon1133** [comment]
what else can I do?

**Comment by Walavouchey** [comment]
wait for a native to review, or wait 2 weeks or so and it'll get merged

**Review by Walavouchey — DISMISSED** [review]
actually, now that i look at it, this article has been rewritten twice (in https://github.com/ppy/osu-wiki/pull/377 and https://github.com/ppy/osu-wiki/pull/2948) since this translation was written, but this pr seems more like clean-up than an actual update. please refer to the [current english version of the article](https://osu.ppy.sh/wiki/en/Modding).

**Comment by Walavouchey** [comment]
yeah

**Comment by yuzupon1133** [comment]
ok done

**Review by TicClick — APPROVED** [review]
merging (no native review after 2+ weeks)

**Pull request merged**
