### PR TITLE
Use LF for markdown files and check with remark

### PR DESCRIPTION
**Pull request by cl8n**
if you already have CRLF stuff checked out, and want to convert all to LF right now, this is what I did:

- make sure you have a clean working dir at index of this branch (or master when it's merged)
- `git ls-files -z '*.md' | xargs -0 rm -f && git reset --hard` - "delete all tracked files and check them out again"

there might be an easier way to do that with git but internet solutions didn't help me

### CODE REVIEW

**Comment by bdach** [comment]
How about seeing `core.autocrlf = input` in `.git/config` for another level of safety? Should prevent `\r\n` from ever getting committed as far as I understand.

**Comment by cl8n** [comment]
there's no way to force changes to git configs like that I think. almost everyone with git is using either `true` or `input` for that, and both will be fine here

**Comment by bdach** [comment]
Oh, local config is lowest priority, ouch. This will have to do I guess, although I'm now wondering if we don't want to set it to `false` for CI so that git doesn't fool it into thinking things are fine by fixing stuff up...

**Comment by peppy** [comment]
For git enforcing, please copy the .gitattributes from https://raw.githubusercontent.com/ppy/osu/master/.gitattributes rather than changing git config. It enforces commit-time line endings and recommends checkout-time line endings for users.

**Comment by peppy** [comment]
Never mind, you already did. Thought that was overlooked when reading the above discussion.

**Pull request merged**
