### PR TITLE
Fixed some wrong information in .osu and .osr file format specifications

### PR DESCRIPTION
**Pull request by goeo-**
### Description

Fixed some wrong information in .osu and .osr file format specifications

### Status

Pending Review: I don't know what `double` translates to in russian so I couldn't fix it there

### Changelog

- Fixed bitfield for key presses in .osr file format
- Fixed milliseconds per beat which is a double and not a float in .osu file format

### CODE REVIEW

**Comment by goeo-** [comment]
Sorry for that commit name! I tried to add a "always used with" note like in Nightcore always being used with DoubleTime, but forgot to set a proper commit name as I did it on the github website using my phone.

**Comment by kj415j45** [comment]
i'll pr zh ver to your branch later

**Comment by Ephemeralis** [comment]
This good to merge?

**Comment by goeo-** [comment]
We're missing french translation (of the "K1 is always used with M1" note) in the .osr file, amd russian translation (of `double`) in the .osu file.

**Comment by osuShiro** [comment]
`(K1 is always used with M1; K2 is always used with M2: 1+4=5; 2+8=10)`
translates to
`(K1 et M1 sont toujours utilisés simultanément; K2 et M2 sont toujours utilisés simultanément: 1+4=5; 2+8=10)`

**Comment by RedNesto** [comment]
I'll be retranslating articles which needs to when this PR is merged (in fact I have already started)

**Comment by osuShiro** [comment]
Let me know when you're done, I'll proofread them.

**Comment by goeo-** [comment]
We only need `double` the programming term's translation [here](https://github.com/goeo-/osu-wiki/blame/6c6bc0fa800cc37c42479f8639d7b195ced0096f/wiki/osu!_File_Formats/Osu_(file_format)/ru.md#L165), for describing Milliseconds Per Beat, which says "десятичное число" right now which I assume means float.

**Comment by goeo-** [comment]
This should be good to merge now.

**Pull request merged**
