### PR TITLE
Delete fr.md

### PR DESCRIPTION
**Pull request by superbenja9**
I am following the contribution guide

### CODE REVIEW

**Comment by TPGPL** [comment]
Could you specify why you are deleting those articles?

**Comment by superbenja9** [comment]
> Could you specify why you are deleting those articles?


I am sorry to have removed these articles but I am following the guide of '' GitHub web interface ''
but I don't understand it well because I can't read or speak English well

**Comment by TPGPL** [comment]
If you want to play with GitHub Interface, you can do it on your fork [here](https://github.com/superbenja9/osu-wiki). Please do not open spam PRs in the future.

**Comment by Lalo611** [comment]
Here are some links for contribution guide updated in spanish, which I assume is your language, if not then just ignore them:
- [Guía de Contribución de la osu!wiki](https://github.com/ppy/osu-wiki/blob/237b326ab23ad1741f24169c49a5e6504c367a64/wiki/osu!_wiki_Contribution_Guide/es.md)
- [Interfaz Web de GitHub](https://github.com/ppy/osu-wiki/blob/237b326ab23ad1741f24169c49a5e6504c367a64/wiki/osu!_wiki_Contribution_Guide/GitHub_Web_Interface/es.md)
- [GitHub para escritorio](https://github.com/ppy/osu-wiki/blob/237b326ab23ad1741f24169c49a5e6504c367a64/wiki/osu!_wiki_Contribution_Guide/GitHub_Desktop/es.md)
- [Problemas Comunes](https://github.com/ppy/osu-wiki/blob/237b326ab23ad1741f24169c49a5e6504c367a64/wiki/osu!_wiki_Contribution_Guide/Common_Issues/es.md)

Ahí está con más detalle lo que tienes que hacer si lo que quieres es contribuir en la osu!wiki

**Pull request closed without merging**
