### PR TITLE
 [EL] Update `Tournaments/Official_support`

### PR DESCRIPTION
**Pull request by Chronicler01**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Review by TicClick — CHANGES_REQUESTED** [review]
please apply changes added to the original article (see the comments above)

**Comment by Chronicler01** [comment]
> please apply changes added to the original article (see the comments above)

I didn't have time to translate Korean, i will start now

**Comment by Chronicler01** [comment]
waiting for Jackpax's feedback, don't merge this

**Comment by Chronicler01** [comment]
i will re-request later

**Pull request closed without merging**
