### PR TITLE
[TH] Help Center

### PR DESCRIPTION
**Pull request by RondoKnight**
I haven't translated all yet. If I am free, I will translate more.

### CODE REVIEW

**Comment by TPGPL** [comment]
Thanks for your contribution, although please refrain from opening PRs with incomplete translations. Also in order to create a new translation, create a new th.md file instead of renaming the English article

**Comment by RondoKnight** [comment]
> Thanks for your contribution, although please refrain from opening PRs with incomplete translations. Also in order to create a new translation, create a new th.md file instead of renaming the English article

Ok Thanks😄

**Comment by paper-toaster** [comment]
There is currently a pr opened (#3680) for the purpose of cleaning up the Help Centre, attempting to translate now may cause conflicts.

**Comment by TPGPL** [comment]
Please reopen the PR when you finish the translation and put it in a seperate file. Note that it might get outdated/deleted quickly because of #3680

**Pull request closed without merging**
