### PR TITLE
[ZH] Add Main Page

### PR DESCRIPTION
**Pull request by cdwcgt**
Add Chinese translation of Main_Page
Status: Ready for being reviewed.

### CODE REVIEW

**Comment by cdwcgt** [comment]
I saw this(This page does not meet the standards of the osu! wiki and needs to be cleaned up or rewritten. If you are able to help out, please consider updating the article!) in https://osu.ppy.sh/help/wiki/Main_Page
Maybe this translation need to change?

**Comment by cl8n** [comment]
the translation is fine for now, that note means the English version needs to be updated first (#2606)

**Comment by cdwcgt** [comment]
ok.I know it.

**Comment by cdwcgt** [comment]
I update the translate of "Support Team"
I change it to "制作团队"

**Pull request merged**
