### PR TITLE
Fix broken image links in osu!academy

### LINKED ISSUE #536: osu!academy image links are broken
After a quick look, osu!academy article has broken image links.

Would do a PR soon for this.

### PR DESCRIPTION
**Pull request by sr229**
### Description

This fixes the broken image links in ``osu!academy``.

### Status
**Finished**; Ready to merge, pending review.

### Changelog

- Fix images using relative path values

### Issues Related

This resolves #536

### CODE REVIEW

**Comment by sr229** [comment]
Sorry for the generic commit message. I forgot to put a commit message.

**Comment by TPGPL** [comment]
Maybe fix translations too? :/

**Comment by sr229** [comment]
:v

**Comment by TPGPL** [comment]
Some banner images on the beginning are broken too?

**Comment by sr229** [comment]
@TPGPL All issues fixed!

**Pull request merged**
