### PR TITLE
[ID] Add Main Page

### PR DESCRIPTION
**Pull request by yansaan**
Hello, i'm translate Indonesian translation for Main_page beacuse not avaiable in Indonesian Language

### CODE REVIEW

**Comment by MegaApplePi** [comment]
This may be outdated by #2625

**Comment by troke12** [comment]
Hey, the main page is /wiki/Welcome not Main Page bro

**Comment by yansaan** [comment]
okay

**Comment by sr229** [comment]
> Hey, the main page is /wiki/Welcome not Main Page bro

@troke12 Main Page *is* the Main page as of today. Welcome is still there but more of a quick start guide role than being the main page before.

**Comment by MegaApplePi** [comment]
@yansaan Can you update this again to match the current one?

**Pull request merged**
