### PR TITLE
Fix empty header in Mappers' Report news post

### PR DESCRIPTION
**Pull request by TPGPL**
also properly fixes a Codacy error

### CODE REVIEW

**Comment by cl8n** [comment]
it's supposed to be a horizontal rule, with the link going to it

**Comment by TPGPL** [comment]
I don't see a harm in making this a header, especially as it makes more sense linking to a header, not a horizontal rule.

**Comment by cl8n** [comment]
I have no comment which one is "better", I just don't think we should change old news posts beyond what's actually broken

**Comment by TPGPL** [comment]
i fixed it because codacy's automatic linter would change it into `# <a id="conclusion></a>` which is obviously wrong. Changing it to something like this doesn't make a difference for potential readers, but prevents breaking something by the lint

**Comment by peppy** [comment]
I disagree with making "conclusion" visible since it wasn't intended to be visible.

**Pull request merged**
