### PR TITLE
[RO] Update `Main_Page`

### PR DESCRIPTION
**Pull request by NiceAesth**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

The changes have been reviewed by certain members of the osu!ro community, all of whom are native speakers.

### CODE REVIEW

**Comment by Australiaa** [comment]
I'm a native speaker, and the changes I've seen are well made.

**Comment by entwastaken** [comment]
I am a native speaker as well, and can confirm the accuracy of the changes.

**Review by TPGPL — APPROVED** [review]

**Review by TPGPL — CHANGES_REQUESTED** [review]
newline at the end of file is missing

**Comment by NiceAesth** [comment]
> newline at the end of file is missing

yep, just saw this. on it

**Comment by NiceAesth** [comment]
Done

**Review by TPGPL — APPROVED** [review]

**Pull request merged**
