### PR TITLE
[ES] Update `Help centre/Account restrictions`

### PR DESCRIPTION
**Pull request by Coolrmsil**
fixed the outdated parts

## Self-check

- [ ] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [ ] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by TicClick** [comment]
I took a closer look, and there are more outdated parts than you fixed. for example, there's a new section titled `What happens if this isn't my first time appealing?` -- see the rest of the accumulated changes @ https://clayton.cc/osu-wiki-status/diff-es-wiki-Help_centre-Account_restrictions

**Comment by r0xANDt0l** [comment]
Same native spanish speaker from Spain here, the translation seems good, and it  also updates the outdated stuff, which was a bit needed

**Comment by TPGPL** [comment]
@Coolrmsil your translation is still outdated comparing to the English version, are you planning to update it at any time?

**Comment by TPGPL** [comment]
since there has been no response in over a month, the translation is still outdated and the diff is small, I'm going to close this PR

if you plan to work on your translation any further, feel free to reopen this PR with requested changes

**Pull request closed without merging**
