### PR TITLE
[ES] Update `Contests`

### PR DESCRIPTION
**Pull request by UnknownOsu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

~~https://i.imgur.com/0AMXe1v.png | I'm not sure if the part that says "osb! Storyboarding Contest" there is some typo in "osb!". I think not and I left that term the same when translating, as I thought it might be a combination of "osu" and "storyboard", forming "osb!", but if it's a mistake, tell me and I'll change that part in the translation.~~

This no longer makes much sense as the names of the contests are left untranslated.

### CODE REVIEW

**Review by agatemosu — CHANGES_REQUESTED** [review]
contest names are not translated

**Comment by TicClick** [comment]
this PR looks abandoned, do you plan to work on it further, or can it be closed?

**Comment by UnknownOsu** [comment]
I think I should just add #9159 and leave the contest names in their native language. 

I will fix that now, or I don't know if I should close this PR and send another one with the changes.

**Review by TicClick — DISMISSED** [review]
merging (no native review for one week or longer)

**Review by TicClick — APPROVED** [review]

**Pull request merged**
