### PR TITLE
Update Fan Art Contest listing

### PR DESCRIPTION
**Pull request by RockRoller01**
- add missing ones (with new flag syntax to not clash with #7601)
- outdate FR
- add contest pages

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)

### CODE REVIEW

**Comment by RockRoller01** [comment]
While adding the contest pages i noticed that these 2 mascot contests are missing, eventho at least one other one is included:
- [ Yuzu's New Look Contest ](https://osu.ppy.sh/community/contests/49)
- [ A Most Manic Art Contest ](https://osu.ppy.sh/community/contests/80)

**Comment by peppy** [comment]
> While adding the contest pages i noticed that these 2 mascot contests are missing, eventho at least one other one is included:
> 
> * [ Yuzu's New Look Contest ](https://osu.ppy.sh/community/contests/49)
> * [ A Most Manic Art Contest ](https://osu.ppy.sh/community/contests/80)
>   Should these be added or is there some reason for excluding them?

I don't see any reason they shouldn't be included.

**Comment by Ephemeralis** [comment]
They're fan art contests just with slightly different outcomes, so yeah, include them.

**Comment by RockRoller01** [comment]
With that those two missing ones should be added, however i was unable to find a results newspost for yuzu 🤔

**Review by TicClick — APPROVED** [review]

**Pull request merged**
