### PR TITLE
Clean-ups

### PR DESCRIPTION
**Pull request by sr229**
this is still a in-progress PR.
this would clean up/ refactor some HTML bindings to Markdown on the Markdown pages.
clean-ups is handled on ``code-cleanups`` branch.

### CODE REVIEW

**Comment by TPGPL** [comment]
Is this completed?

**Comment by sr229** [comment]
unfortunately, it hasn't due to the complexity of some files. I'll try to resume when I have the chance

**Comment by TPGPL** [comment]
resolve conflicts :+1:

**Comment by sr229** [comment]
clsoing because activity is stale

**Pull request closed without merging**
