### PR TITLE
Improved osu!wiki contribution guide

### PR DESCRIPTION
**Pull request by ElectrifyPro**
### Description

Simplified the text and made it easier for new users to figure out how to contribute.
Updated two outdated images and deprecated an image.

### Status

Finished

### CODE REVIEW

**Comment by kj415j45** [comment]
duplicate with / block by #513

**Comment by ElectrifyPro** [comment]
Is this a major problem?

**Comment by kj415j45** [comment]
well, 513 rewrite the whole owcg, your pr will conflict with it

**Comment by ElectrifyPro** [comment]
So closing this PR would probably be best

**Comment by sr229** [comment]
This article is subject to rewrite since it's too verbose.

**Pull request closed without merging**
