### PR TITLE
Add guideline about crediting media to RC

### PR DESCRIPTION
**Pull request by cl8n**
https://osu.ppy.sh/community/forums/topics/1191040

also fixes the TODO comment in the list above that didn't refer to anything (original referenced rule got deleted, I think)

### CODE REVIEW

**Comment by peppy** [comment]
This should only be added if it references the part where you should have explicit permission (or correctly licenced) media in the first place. The licensing for it should detail how attribution should be done.

**Comment by peppy** [comment]
I think this reads better now 👍🏻 .

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Is this in a draft status for a reason?

**Comment by cl8n** [comment]
wanted to make sure hobbes2 (OP of the rc thread) thought this wording was good too, just got their approval

**Pull request merged**
