### PR TITLE
[PL] History of osu! - '09-'10

### PR DESCRIPTION
**Pull request by vistafan12**

### CODE REVIEW

**Comment by sr229** [comment]
do not proceed with this as @TPGPL  and I have a planned rewrite for the HOO articles

**Comment by vistafan12** [comment]
Ok...

**Comment by sr229** [comment]
requesting closure for PR @TPGPL or @Repflez 

(Reason: PR is stale)

**Comment by Repflez** [comment]
Closing due to stale PR. Open a new PR if you still wish to have this added.

**Pull request closed without merging**
