### PR TITLE
[DE] Remove `bestätigt` as a translation for `approved` from the ASC

### PR DESCRIPTION
**Pull request by FreezyLemon**
This translation isn't used anywhere in the wiki. `Approved` should just be used as-is.

## Self-check

- [X] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- [x] *(translations only)* The changes are reviewed on GitHub [by a fluent speaker](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#review)

### CODE REVIEW

**Comment by Walavouchey** [comment]
@The-Last-Cookie

**Comment by Walavouchey** [comment]
even if it's not used, are the other translations (ranked, qualified, etc.) used? why is "approved" an edge case?

**Comment by FreezyLemon** [comment]
> even if it's not used, are the other translations (ranked, qualified, etc.) used? why is "approved" an edge case?

`ranked` is mostly used as-is, `gerankt` is an anglicism, not a translation.
An argument could be made for `qualified` and `loved` to also never be translated, but these translations make sense and are understandable. `bestätigt` is technically one correct translation, but I doubt users would understand what a `bestätigte Beatmap` is.

**Comment by The-Last-Cookie** [comment]
@Walavouchey It's currently in debate in the German osu! discord and I will take a closer look at it as soon as I have time.

**Comment by The-Last-Cookie** [comment]
In fact, I do agree that `bestätigt` is not a good translation.

While reading through the discussion, I prepared a list of words that I could *personally* see being used going forward. It was compiled with the suggestions in said discussion as well as my own considerations.

| English | German |
| :-: | :-- |
| graveyard | Friedhof |
| qualified | qualified, qualifiziert |
| pending | ausstehend |
| WIP | WIP, in Arbeit |
| loved | loved, (in der Community) beliebt, (von der Community) gewürdigt/geliebt |
| approved | approved, angenommen, zugelassen |
| ranked | ranked, gerankt, freigegeben |
| unranked | nicht freigegeben, nicht gerankt |

After taking a step back from this, I realise most players are preferring to keep the original words as proper nouns which I am fine with (for the most part at least). I can understand why one would rather use no translation for some of these terms, as there is no real fitting word for these in German that carry over the same meaning and expression (or are just pretty common by now like WIP).

In the end, we need to reach a consensus and if a major part of the community decides to not use what I suggested above, then so be it.

**Comment by FreezyLemon** [comment]
This is way out of scope. Can we keep it to my teeny tiny change for now?

We can change the other translations later, thanks

**Review by The-Last-Cookie — APPROVED** [review]
I didn't have the intention to change this PR any further. My intention was to publish my opinion about the topic at hand.

So, my post in the discord still stands for discussion.

**Comment by FreezyLemon** [comment]
Alright, let's move further discussion to Discord.

**Review by cl8n — APPROVED** [review]

**Pull request merged**
