### PR TITLE
Vietnamese translate for Hybrid play style

### PR DESCRIPTION
**Pull request by Jackie-Potato**

### CODE REVIEW

**Comment by DoryanR** [comment]
Why delete the English file? It must be kept, otherwise the article will no longer be available.

**Comment by Jackie-Potato** [comment]
> Why delete the English file? It must be kept, otherwise the article will no longer be available.

oh sorry um, this is my first time doing something like but um how can i do it

**Comment by DoryanR** [comment]
In your case I can advise you to take the content of the English file, to recreate it and to paste its contents on the freshly created file.
This is the simplest solution, which comes to my mind immediately.

**Comment by Jackie-Potato** [comment]
> In your case I can advise you to take the content of the English file, to recreate it and to paste its contents on the freshly created file. This is the simplest solution, which comes to my mind immediately.

thanks

**Pull request closed without merging**
