### PR TITLE
Rework FAQ

### LINKED ISSUE #1563: FAQ needs a rewrite
https://osu.ppy.sh/help/wiki/FAQ

I probably won't have a question about the game modes let alone the origin of the game. It was also copied and pasted from the game modes article. There are other stuff ("Common issues and questions" section on FAQ?) which I won't say, but it definitely needs a update.

### PR DESCRIPTION
**Pull request by Joehuu**
Applied formatting corrections and removed redundant information entirely.

~Questions are now bolded by itself, not in headers. *(is it better, idk)*~ Waiting for suggestion.

- Closes #1563

---

### CODE REVIEW

**Comment by Joehuu** [comment]
Will split this PR.

**Comment by Joehuu** [comment]
Nvm, the commits seem good so I'm putting this back. I might need to revert/update some stuff.

**Comment by sr229** [comment]
Last activity is February 19, Please confirm activity or any active wiki admin should close for stale PR.

**Comment by Joehuu** [comment]
Yeah, this is stale.

**Pull request closed without merging**
