### PR TITLE
Add New Featured Artist: Rivers of Nihil newspost

### PR DESCRIPTION
**Pull request by Ephemeralis**
💀 🎵

### CODE REVIEW

**Comment by Coppertine** [comment]
https://twitter.com/ItsWinterOsu/status/1214266130791055360
If you want shoutout, it's SILENCEPLAYER who guessed the earliest

**Comment by Ephemeralis** [comment]
oh wow, someone actually got it? nice!

**Comment by Ephemeralis** [comment]
can you link the tweet/comment where SILENCEPLAYER got it first? @Coppertine

**Comment by Coppertine** [comment]
Linked in message above

**Comment by Coppertine** [comment]
https://twitter.com/Asvesniis1/status/1214270348272652290
This person just messaged it 10 minutes after btw

**Comment by I-Nix-I** [comment]
POGGERS mate

**Pull request merged**
