### PR TITLE
[ZH] Fix typos in `Ranking_criteria/osu!taiko`

### PR DESCRIPTION
**Pull request by ThomasZQY**
Corrected some mistakes in Chinese version of o!t rc.

Most of the changes are due to conflictions with main version (English version) or simply common sense.

Deletion in line 150 is due to "oox, oxx" being paterns of length 3, not over, and hence not included in precondition.
150行中删去“oox、oxx”是因为这是3连，不包含在”超过3连“的前提条件中。

### CODE REVIEW

**Comment by ThomasZQY** [comment]
Oh just noticed there were already edited by hivie. (but I didn't see them get changed on osu wiki website)

Just ignore this one anyway.

**Comment by CloneWith** [comment]
So welcome to GitHub!
You've corrected a typo in the translation, which isn't included in Hivie's PR, then I think yours should be kept.

欢迎加入 GitHub！
与 Hivie 的请求相比，你还修改了翻译中的笔误，因此我想应该保留你的。

**Comment by CloneWith** [comment]
> but I didn't see them get changed on osu wiki website

在更改出现在网页前，需要请求先被合并。你可以先用支持 Markdown 的编辑器预览。

Before changes are applied to the website, the PR should be merged first. You can try to use a editor supporting Markdown to preview your changes.

**Comment by ThomasZQY** [comment]
Sorry I'm still new to github and couldn't fully understand what you meant. Am I supposed to do something now (did I miss doing something), or should I just wait until it is applied?

**Comment by CloneWith** [comment]
> Am I supposed to do something now (did I miss doing something), or should I just wait until it is applied?

You have done your part perfectly. Just wait for the maintainer to merge it 👍

---

To learn further, you can read the [GitHub help documents](https://docs.github.com/) and [the contribution guide of osu! wiki](https://osu.ppy.sh/wiki/zh/osu!_wiki/Contribution_guide), to gain a clearer insight into the contribution process.

Hope this helps!

我英语说得可能不太好，请见谅！

**Review by CloneWith — APPROVED** [review]

**Review by TicClick — APPROVED** [review]
please don't hesitate to ask for a merge in the `#osu-wiki` channel if you consider your PR ready or don't realy know what to do next

**Pull request merged**
