### PR TITLE
Fix table formatting remark warnings

### PR DESCRIPTION
**Pull request by agatemosu**
## Self-check

- [x] The changes are tested against the [contribution checklist](https://osu.ppy.sh/wiki/osu!_wiki/Contribution_guide#self-check)
- `SKIP_OUTDATED_CHECK` because some articles doesn't have that extra space

### CODE REVIEW

**Comment by Walavouchey** [comment]
please post what script you've used for these changes

**Comment by cl8n** [comment]
the list changes aren't quite right as explained in that long discord msg I mentioned you in earlier. the table is part of the list item and so should be indented. you can choose whether the list is spread (empty lines between each list item + block child of list item) or not (no empty lines) but probably keep spread since that's what they were already.

as for the other table formatting changes, they are not wrong and I'll merge them but I feel like I've already told you that this type of PR that can be automated by remark already is not very helpful...

**Comment by agatemosu** [comment]
> please post what script you've used for these changes

I used the VS Code search and replaced manually

**Comment by agatemosu** [comment]
> the list changes aren't quite right as explained in that long discord msg I mentioned you in earlier. the table is part of the list item and so should be indented. you can choose whether the list is spread (empty lines between each list item + block child of list item) or not (no empty lines) but probably keep spread since that's what they were already.

reverted

**Comment by agatemosu** [comment]
I force-pushed because I wanted to see the diff of github desktop to make it faster

**Review by cl8n — APPROVED** [review]

**Review by Walavouchey — APPROVED** [review]

**Pull request merged**
