### PR TITLE
Remove tooltips from links in news posts

### PR DESCRIPTION
**Pull request by TPGPL**

### CODE REVIEW

**Review by TicClick — APPROVED** [review]

**Comment by peppy** [comment]
Any reason this is split up into specific sections of articles?

**Comment by TicClick** [comment]
it's to speed up the review process. the first pull covers only regular articles which aren't protected by the code owners file (there are about 450 files affected), while these two (news/help centre) are <=20 files total

**Comment by peppy** [comment]
I dunno, I see it as the opposite. If it's all in one place with one command I can run and diff/compare against it's less effort for me. And if I'm disagreeing with this, it's going to be on all or none, not just on new posts for example.

Whatever works i guess.

**Comment by Ephemeralis** [comment]
Why are we removing these, exactly? Do they break something?

**Comment by TicClick** [comment]
> Why are we removing these, exactly? Do they break something?

from #6060:

> contrary to #6012
> 
> since the only reason for link tooltips to exist is making the external links distinguishable from regular wikilinks, we decided that it will be better to remove them completely and leave the matter for osu-web to add a native indicator for such links like on Wikipedia
> 
> image

**Review by TicClick — APPROVED** [review]

**Pull request merged**
